### ISSUE TITLE
Typescript Definitions file

### ISSUE THREAD

**Issue by tel** [dekujs/deku#101]
I've drafted up a Typescript d.ts file for Deku's API as I've been able to understand it via about 30 minutes reading the docs. I doubt that the segmentio team would like to maintain definitions files along with the deku codebase if they're not using TypeScript, but it could be useful in a few ways

* It's at least informative: this is what I understood from reading the docs quickly just today. Missing components or invalid assumptions could be places to improve the docs
* It's potentially a good information source for new users

In any case, I wanted to share it with the Deku team. I really appreciate the simplicity of the design you guys have landed on and I think the definitions file shows that as well.

https://gist.github.com/tel/a4b0980db350096afd53

**Comment by anthonyshort** [comment]
Nice! It's a good way to see all of the parts of the API a user will need to know. The smaller we can make that definition, the easier it will be to learn. 

We don't really use Typescript, but this could live in the docs folder. It could be nice to get a d.ts file for the virtual elements too.

**Comment by tel** [comment]
Yeah! I think docs are probably as much as I would have expected to be valuable to Deku as a project, though we might evaluate Deku for us with TypeScript and it's ability to have a well-typed API is a big boon here.

Generally, I think the forcing function to shrink the public API is a good side effect of building definition files like this.

Right now treating the virtual elements as abstract is kind of a nice property—the only thing you can do with them is assemble the tree by returning them and passing them to `element` as children. What are the use cases for examining or working with virtual elements?

**Comment by anthonyshort** [comment]
There really shouldn't be any reason to touch them manually. In fact, you shouldn't. It's only used internally at the moment (which is why it's not it's own repo) but speccing those out could help spot unneeded complexity and could make it easier for other people to implement.

**Comment by tel** [comment]
Hm, that's definitely true. There's sort of a tradeoff here in exposing a public API with exposed or abstract types. I'm usually a believer in having both, but there needs to be a way of denoting that idea: "you probably shouldn't, as a user, even know that there's an API on virtual elements".

I'll ask around the TS community and figure out best practices for achieving that sort of thing.

**Comment by tel** [comment]
Offhand, looking at [`ComponentNode`](https://github.com/segmentio/deku/blob/master/lib/virtual.js#L121),  [`ElementNode`](https://github.com/segmentio/deku/blob/master/lib/virtual.js#L139), and [`TextNode`](https://github.com/segmentio/deku/blob/master/lib/virtual.js#L156) it seems that `VEl` is the union of those three, yes?

**Comment by tel** [comment]
Then discrimination is done via the `type` member? Is there any reason why that's used instead of something like `instanceof`?

**Comment by lancejpollard** [comment]
Yeah `VEl` seems like it should be the union of those three. It would be sweet to have these formal definitions.

**Comment by lancejpollard** [comment]
@tel Possibly was like that for performance, but don't think we ever benchmarked haha. But yeah it's just for discrimination, could definitely be changed if it simplifies it.

**Comment by anthonyshort** [comment]
I'd say it's more of a style thing, so that we didn't need to rely on constructor types which are bit of a hack in JS anyway. Plain objects would be serializable to JSON too I guess

**Comment by lancejpollard** [comment]
Ah yeah JSON too, that's true

**Comment by tel** [comment]
Offhand I'd write something like this in Typescript (a la Scala sealed case classes)

```typescript
class VNode<P, S> {};

class ComponentNode<P, S> extends VNode<P, S> {
  key: string;
  props: P;
  component: Component<P, S>;
  // children... this gets placed on Props now which is a little harder to type
}

interface Dict { 

class ElementNode<P, S> extends VEl<P, S> {
  attributes: { [name: string]: string }; // This is overly strict
  tagName: string;
  children: Array<VEl<any, any>>;
  key: string;
}

class TextNode<P, S> extends VEl<P, S> {
  data: string;
}
```

There are a few messes there around how to properly denote existential types in Typescript (the `any` bit).

The `type` member could be kept just along with the (already existent) invariant that `type` doesn't lie. JSON serialization makes a lot of sense as a design constraint here.

**Comment by tel** [comment]
The other option would be to ditch the `VEl` superclass and call it `type VEl = ...` but type aliases don't support generics. That's sort of just too bad, though.

**Comment by tel** [comment]
TypeScript embraces constructor types more than raw JavaScript I suppose. The arrangement above with the `VEl` superclass allows the use of type guards to get a weak kind of ADT pattern matching.

```typescript
function virtualName(vel: VEl): string {
  if (vel instanceof ComponentNode) {
    return vel.component.id;
  } else if (vel instanceof ElementNode) {
    return vel.tagName;
  } else if (vel instanceof TextNode) {
    return vel.data;
  } else {
    console.log("VEl exhaustiveness invariant violated: " + vel.toString())
  }
}
```

**Comment by tel** [comment]
Somewhat significantly improved the definitions file in the same gist linked in the parent. New bits include

* Reordered to better reflect core API
* Improved documentation
* Better typing for the `element` function
* Renamed `Tree` to `Application` to match the classes
* Renamed `VEl` to `VirtualNode` to match the classes
* Improved `Evented` interface to provide exactly the right kind of event type to the listeners

**Comment by anthonyshort** [comment]
Looks great to me! @lancejpollard what do you think? 

Do you want to PR that into the project and we can get it merged it in.

**Comment by lancejpollard** [comment]
Yeah this looks awesome. Definitely would be cool to include in the repo.

**Comment by anthonyshort** [comment]
One thing I just noticed, https://gist.github.com/tel/a4b0980db350096afd53#file-deku-d-ts-L261 The event handlers are passed the `Component` as the second param. 

@tel I'm not too sure how these files work so if you could add it to the repo that would be great :)

**Comment by tel** [comment]
I'll create the PR shortly.

The event handlers I have being passed in here: https://gist.github.com/tel/a4b0980db350096afd53#file-deku-d-ts-L30. I think that's correct: that when creating a new ComponentNode or ElementNode you may include event handlers in the props? This current design means that people write components where the prop type `P` includes the event handler configuration they desire.

I think I'll try to include an example in the PR, too, though I may just set up the PR quickly now to get it out of the way.

**Comment by wgv-sethlivingston** [comment]
Where is this file?

**Comment by pocka** [comment]
This file seems to be removed at v2 (Maybe everything placed in v1's `docs` directory were deleted).

If you are using typescript 2.x, try `@types/deku` .
