### ISSUE TITLE
non jsx example

### ISSUE THREAD

**Issue by flosse** [dekujs/deku#111]
Would you mind to add a complete example that doesn't use jsx?

**Comment by chrisbuttery** [comment]
If you look at the `counter` [example](https://github.com/segmentio/deku/blob/master/examples/counter/index.js), you would just change the following:

```js
let counter = tree(
  <Counter onAnEmittedEventFromCounter={ doSomething }></Counter>
);
```
to
```js
let counter = tree(
  element(Counter, { onAnEmittedEventFromCounter: doSomething })
);
```

**Comment by chrisbuttery** [comment]
[#112](https://github.com/segmentio/deku/pull/112)

**Comment by flosse** [comment]
cool! thx!

**Comment by anthonyshort** [comment]
We should probably add some better docs for this too. So I might reopen it so we remember

**Comment by flosse** [comment]
BTW: I like it using coffee-script instead of JSX
```coffee
Foo =
  render: (c) ->
    { props, state } = c
    element 'ul', class: "foo",
      element 'li', class: "bar", props.children
```
And if there would be a react like `deku.DOM` shortcut, it would look even nicer:
```coffee
{ ul, li } = deku.DOM
Foo =
  render: (c) ->
    { props, state } = c
    ul class: "foo",
      li class: "bar", props.children
```
