### ISSUE TITLE
hybrid rendering example

### ISSUE THREAD

**Issue by tracker1** [dekujs/deku#114]
It would be nice to see an example that used hybrid rendering...

* Initial request for `/foo/bar` received on the server
  * Server processes routing request, and retrieves related resources/state
  * Server encodes state for client
  * Server renders full page to the browser - with state
* Client hydrates state, and raises an event for first load
* Client then facilitates any further actions from user

**Comment by anthonyshort** [comment]
I know @dominicbarnes is working on building out a very fleshed out example. Including a koa server that renders it on the server would be great. @stevenmiller888 has [this template](https://github.com/stevenmiller888/keku) that you could look at too.

**Comment by tracker1** [comment]
@anthonyshort the template by @stevenmiller888 doesn't actually do any server-side rendering... it only outputs the index.html file for all requests not to a static file.  Which will work for client rendering, but not server...

**Comment by dominicbarnes** [comment]
The hardest part of joint rendering is the dependencies. I normally use duo/component for client-side code, which won't use the same dependencies as node/npm. (this isn't a deku problem, just a problem in general)

If I do come up with a good example here, it'll probably be using browserify just for the sake of simplicity.

**Comment by tracker1** [comment]
@dominicbarnes Fair enough... also worth consideration if you're thinking of browserify, would be BabelJS (for 6/7 to 5 conversion) ... I understand about the dependencies... I'm running my client/server code (currently react/flux) through the same API interfaces with isomorphic-fetch, which makes most of it consistent.  Then with babeljs & browserify... It works, but would love the cleaner constructs that deku brings to the table.

I'm going to try and find some time early next week to play with deku a bit to see if I can get a de/rehydration working for state/properties.

**Comment by dominicbarnes** [comment]
I'm working on a TodoMVC version of deku right now. (it's being built with Browserify + Babelify)

Once I finish the client-side version, I'll start on a hybrid version alongside.

**Comment by dominicbarnes** [comment]
I've added a _very_ basic hybrid-rendering example [here](https://github.com/dekujs/todomvc).

The TodoMVC example is geared toward client-side frameworks, so the data-persistence is only `localStorage`. However, it still renders the default HTML and then the client-side Deku script re-renders the page after it loads. :)

Better examples will be coming around in the near future.

**Comment by chrisbuttery** [comment]
Great example @dominicbarnes. :+1:

**Comment by anthonyshort** [comment]
Just added this to the Readme. We can probably close this here for now and follow that repo.
