### ISSUE TITLE
Add option to DOM renderer to empty container before initial render

### ISSUE THREAD

**Issue by dominicbarnes** [dekujs/deku#120]
When doing hybrid-rendering, I discovered that simply rendering client-side created a duplicate of my UI. (since it appends the new node after the one rendered by the server)

Can we add an option (like `emptyContainer`?) that tells deku to clear out the container before that initial render? (thus preventing this [little bit of awkwardness](https://github.com/dekujs/todomvc/blob/master/client/index.js#L11))

**Comment by anthonyshort** [comment]
That could work. Maybe it could render and then replace the element instead so it'll be instant. The other option would be to just diff it.

**Comment by anthonyshort** [comment]
Is there a noticeable flash if you empty the container and then render into it?

**Comment by dominicbarnes** [comment]
Not that I remember, I'll take a look in the morning.

**Comment by dominicbarnes** [comment]
When the client-side renders the same thing as the server-side, I don't see any flash. Since the TodoMVC app uses localStorage to persist, it needs to retrieve from there after the page loads, then you do notice a slight flicker. 

Since the normal use-case is to pre-render the same thing server-side, I don't think this is a problem. I'm open to attempting a diff on the existing HTML content, but afaik there are weird edge-cases there since we can't assume that the contents of the container are all controlled by deku.
