### ISSUE TITLE
window listener in `afterMount` gets called once immediately

### ISSUE THREAD

**Issue by lambtron** [dekujs/deku#124]
```
App.prototype.afterMount = function(el, props, state) {
  window.addEventListener('keyup', console.log('hi'));
};
```

Attaching event listener to `window` will always get called once immediately, even if the event was not triggered.

**Comment by anthonyshort** [comment]
`window.addEventListener('keyup', console.log('hi'))`

This will always evaluate `console.log('hi')` every time. I think you're looking for `window.addEventListener('keyup', console.log.bind(console, 'hi'));`

That's also using the older API :)

**Comment by lambtron** [comment]
awesome!! :)
