### ISSUE TITLE
Passing props to initialState hook

### ISSUE THREAD

**Issue by blup** [dekujs/deku#125]
I know you can "just use javascript" (issue #46) and respond to props on render, but there are some scenarios where having props available to initialState are necessary. For example, any event callbacks set in render will get the unmodified state. In any case, its a change that should approach you to the react api.

**Comment by anthonyshort** [comment]
If you can provide a solid use-case for it then we can easily add it. We didn't pass it in so that people didn't try and compute state from the props.

**Comment by blup** [comment]
From my experience with React, the component state is the only source of truth. If I want to have a configurable component, the only way to modify the initial state from the outside (parent component) is through props. I could compute the state in render, but the event handlers wouldn't have an up-to-date 'initial' state. This is a bit of a contrived example: http://pastebin.com/gLN43U1f .

**Comment by anthonyshort** [comment]
Any reason you wouldn't just do something like this?

```js
let {props,state} = component
set({ value: (state.value || props.initialValue) +1 })
```

And you could just abstract this into a function to get `value` given a `component` and use it in both functions

```js
function getValue (component) {
  let {props,state} = component
  return state.value == null ? props.initialValue : state.value
 }
```

**Comment by blup** [comment]
I'm not sure I understand, are you saying i should set({value}) in render, causing a second render? Besides it seems overcomplicated to go checking if every state value is present or not at render time. Why not just define your intentions in the initialState?

**Comment by anthonyshort** [comment]
Ah sorry, I meant in the event handler:

```js
function onClick(event, {props, state}, updateState) {
  updateState({ value: (state.value || props.initialValue) +1 })
}
```

But I suppose something like this would be clearer:

```js
function initialState (props) {
  return {
    value: props.intialValue || 0
  }
}
```

**Comment by anthonyshort** [comment]
This will go out in the next version :)
