### ISSUE TITLE
Component context in hooks

### ISSUE THREAD

**Issue by blup** [dekujs/deku#126]
From what I've seen in the docs, and issue #105, the functional 'style' of this library suggests you to place handlers/callbacks inside their respective function, creating closures. Is there a reason why you can't pass the component as context to the hooks? (line #965 render.js)
````javascript
entity.component[name].apply(entity.component, args)
````
Since we're dealing with a simple object here, you could then bind `{onClick: this.onClick}` in render. It would allow for other styles of code. Besides, closures are really slow.
http://jsperf.com/closure-vs-global-variable/7
http://jsperf.com/closure-vs-property/12

**Comment by anthonyshort** [comment]
If you're talking about just event handlers, they already get given the `component` object as the second parameter (https://github.com/dekujs/deku/blob/master/lib/render.js#L1154) Looks like we haven't documented this very well. You won't need to use closures if you do it that way.
