### ISSUE TITLE
No DOM element in afterMount

### ISSUE THREAD

**Issue by blup** [dekujs/deku#127]
I'm trying to access an element's innerHeight/Width in afterMount, but it seems we're given the virtual-dom representation of the element, or am I wrong? In any case, since its not in the dom yet, it doesn't have any dimensions.

**Comment by anthonyshort** [comment]
It gets the element, but it hasn't been placed in the DOM yet. This is a bug #110 that should be fixed soon.

**Comment by anthonyshort** [comment]
Closing as a duplicate for now
