### ISSUE TITLE
Composing Elements

### ISSUE THREAD

**Issue by Frikki** [dekujs/deku#128]
Often when building a UI, components share common functionality. For example, both an `input` element and a `button` element could have an `onFocus` event listener and share the same focus handler. However, using deku, it seems as that event handlers can _only_ be declared _within_ the render method, thus, eliminating shared handlers (or using `this.focusHandler` lets me declare the handler on the element outside the `render` method). Is there a way to circumvent this "requirement"?

**Update**

I found one way to forward the call, but it seems very hacky, and I really dislike the use of `this`.

```javascript
import { element } from 'deku';

function sharedFocusHandler( event, component, setState ) {
    console.log( component );
}

let Button = {

    focusHandler: sharedFocusHandler,

    render: function render( component ) {
        let { props, state } = component;

        return element(
            'button',
            {
                onFocus: this.focusHandler
            },
            [ props.text ]
        );
    }
};

export default Button;
```

**Comment by Frikki** [comment]
No worries, I found a couple of ways to deal with this using decorators.

**Comment by anthonyshort** [comment]
Something like this should work without needing to do anything tricky:

```js
let button = {
  render (component) {
    return element('button', { onFocus: focusHandler }, [props.text])
  }
}

let input = {
  render (component) {
    return element('input', { onFocus: focusHandler }, [props.text])
  }
}

function focusHandler (event, component, setState) {
  console.log(component)
}
```

The component will be different depending on which element calls focus. Does that work for you?

**Comment by Frikki** [comment]
Yes, that works, but what I want is a bit more composed. I am finding a way, thanks.

I think the initial problem was when I used JSX-style: 

```javascript
export Button = {
  render (component) {
    let { props, state } = component;

    function focusHandler( event, component, setState ) {
      console.log( component );
    }

    return (
      <button onFocus={ focusHandler }>
        Hello, deku!
      </button>
    );
  }
}
```

I wasn’t able to move the `focusHandler` out of the `render` method.

**Comment by Frikki** [comment]
Is it possible to dynamically bind an event listener to a component through another event handler? I can of course get `event.target`, which would bind it directly to the DOM node, but I am I right in my assumption that the newly bound event listener won’t emit `event, component, setState` as an initial bound event listener does?

**Comment by Frikki** [comment]
Disregard my last comment. I am stuck in an old pattern-paradigm. Of course, I should just `setState` and update the component accordingly.

**Comment by anthonyshort** [comment]
Yup, just use that state in the render function each time. I find myself tripping up and still trying to write imperatively too. Glad you got it working!

**Comment by Frikki** [comment]
@anthonyshort I came from React which was, IMHO, taking a wrong approach with classes, and from what I gathered, they want to take advantage of the new ES6 class feature. It feels like turning EcmaScript into Java. I think deku will save my sanity.
