### ISSUE TITLE
Make Examples Live?

### ISSUE THREAD

**Issue by imton** [dekujs/deku#129]
It'd be really useful to have the example live, even hosted under github.

**Comment by anthonyshort** [comment]
Maybe it's time we just moved the examples to their own repo and they can live on github pages. Less code in the project is :+1: from me

**Comment by jiyinyiyong** [comment]
I think the code is broken, `component` is not defined in the file, and unlikely a function:

https://github.com/dekujs/deku/blob/master/examples/events/index.js#L26
```js
var MouseDown = component(function(props, state, send){
  function down() {
    send({ down: true });
  }
  function up() {
    send({ down: false });
  }
  var classes = {
    'active': state.down === true
  };
  return dom('div.box', { class: classes, onMouseDown: down, onMouseUp: up }, [
    'Mousedown / Mouseup'
  ]);
});
```
