### ISSUE TITLE
Join the Virtual DOM Benchmark game

### ISSUE THREAD

**Issue by kolya-ay** [dekujs/deku#130]
The playground is [here](http://vdom-benchmark.github.io/vdom-benchmark/). It would be great to see deku there not only for speed comparison but also for having an up-to-date list of different *virtual dom*   implementations and related approaches

**Comment by anthonyshort** [comment]
Interesting! I wonder how it compares these implementations in terms of "components". Many of the vdom implementations don't have the concept of sub-trees so comparing them is tricky. The benchmarks don't seem to include a large amount of nodes either. When diffing it can become exponentially slower as the number of leaf nodes increases.

Smaller vdom libraries that just do diffing but don't have the idea of components will perform better in this test. Libraries like React and Deku are factoring in components so they'll always be slower in this sort of test.

A true comparison would be to have a whole app and constantly re-render it. Some of the vdom implementations would be rendering everything every time, whereas others will only be rendering sub-trees so the results would be different.

There's also much, much more to it than just the performance of the diffing. There's still the developer experience to factor in to determine if something is 'good'.

**Comment by kolya-ay** [comment]
Yeah, I completely agree. However the addition of deku might be a first step. Both mercury (virtual-dom based) and mithril have a notion of *component/thunk* already, thus it might be worth to compare it that way.

**Comment by jails** [comment]
Since this benchmark is focused on the diffing/patching part only, the React implementation rely on `ReactElement` (not the component layer) https://github.com/vdom-benchmark/vdom-benchmark-react/blob/master/web/js/main.js so it's almost fair ;-)

**Comment by anthonyshort** [comment]
I've got a deku version ready, but I can't get the tests to run locally. If you can add some more docs that explains how it works locally I should be able to test it and push it up :)

**Comment by jails** [comment]
I personnaly cloned https://github.com/vdom-benchmark/vdom-benchmark and added a new entry at the end of `web/config.js`. Something like the following should work in your case:
```js
    {
      "name": "deku",
      "url": "https://github.com/dekujs/deku/",
      "benchmarkUrl": "http://localhost/vdom-benchmark-deku/build/"  # <-- a local url
    }
```
And then I runned `gulp` to generate the build. Finally I was able to run benchmarks locally using `http://localhost/vdom-benchmark/build/` with my added entry.

**Comment by anthonyshort** [comment]
Done!

https://github.com/vdom-benchmark/vdom-benchmark/pull/9
https://github.com/dekujs/vdom-benchmark

![screen shot 2015-05-27 at 9 11 37 am](https://cloud.githubusercontent.com/assets/36125/7841301/8995790e-0450-11e5-870b-a63fef0e1dcf.png)

I don't think it's a great benchmark, it really should do more than just render a whole new vnode in update. The real test would be a giant virtual tree that has sub-tree updates that trigger really fast.

**Comment by lancejpollard** [comment]
:+1:

**Comment by jails** [comment]
Awesome :+1: !
