### ISSUE TITLE
Why fast.js?

### ISSUE THREAD

**Issue by Frikki** [dekujs/deku#134]
I wonder why the decision was made to include fast.js. Sure, some extreme benchmarks show a performance gain over native implementation, but is 2 Mops/s vs 1.5 Mops/s really an issue? The inclusion of fast.js _significantly_ increases the size of the build and, thus, the load time. So who exactly is gaining from this inclusion?

**Comment by anthonyshort** [comment]
i think we're actually only using a couple of functions from it. We could pretty easily replace those with smaller modules. When I implemented it I didn't know how much of it I was going to use, the goal was to just get everything super fast. 

If you want to open a PR replacing the forEach and reduce (there might be a couple more) we could switch to using specific modules. It's probably still valuable to use modules that are faster than the native version in the renderer though. 

We really need to get some solid benchmarking tests, that would answer everything.

**Comment by Frikki** [comment]
It looks like you’ve been caught in the infamous [premature optimization](http://c2.com/cgi/wiki?PrematureOptimization) syndrome, which is mostly considered, as Donald Knuth once wrote, "the root of all evil". I would suggest to optimize only on issues that have significantly shown to be performance bottle necks.

Naively, I believe that the real performance gain from fast.js would be server-side.

**Comment by anthonyshort** [comment]
Yeah I think so, at least partially. We have needed to improve the performance of our own app by tweaking a few of these things inside Deku. As long as common use-cases render under 16ms, it's fast enough.

**Comment by Frikki** [comment]
Did fast.js make any notable difference on your app? If so, which differences did you see? How about app load time?

I will, when I get a little time, make a PR. Btw., thanks for your prompt responses and a cool piece of software.

**Comment by anthonyshort** [comment]
We noticed that a few changes to the way it iterated sped up rendering large lists, which makes sense as larger trees means more iteration. It particular sped up things like sorting and filtering a large list which requires a lot of diffing if you're not using keys.

And thanks! Glad you're liking it. We always appreciate people taking to time to help us iron out some of these kinks. We really want it to be a project with a lot of community around it building it.

**Comment by Frikki** [comment]
I’ve made a PR here https://github.com/dekujs/deku/pull/137
