### ISSUE TITLE
validateProps and propTypes

### ISSUE THREAD

**Issue by Frikki** [dekujs/deku#139]
While useful, this functionality lacks the ability to validate "nested/sub" props. For example, it can, for various reasons, be useful to group properties:

```javascript
props = {
  modifiers: {
    type: 'link'
    disabled: false
  },
  eventListeners: {
    onClick: handleClick
  }
}
```

Though a rather simplistic example, this shows a use case that `validateProps` and `propTypes` don’t seem to be able to handle. In React, for example, it is possible to define the prop types for "nested/sub" props. I believe such a feature is very useful and should be considered incorporated. At least, I can think of several advantages by being able to divide properties into sections and have the sub-props validated, e.g., easy merging of selected prop sections to state sections and prevention of conflicting prop names.

**Comment by anthonyshort** [comment]
What would be a nice syntax for this? We could keep it flat:

```js
let propTypes = {
  'modifiers.link': { type: 'string' },
  'modifiers.disabled': { type: 'boolean' }
}
```

or we could do something more advanced to define types.

```js
let propTypes = {
  'modifiers': { 
    type: {
      link: { type: 'string' },
      disabled: { type: 'boolean' }
    }
  }
}
```

I don't mind this because you can split it up and re-use types:

```js
let modifierType = {
  link: { type: 'string' },
  disabled: { type: 'boolean' }
}

let listenersType = {
  onClick: { type: 'function' }
}

let propTypes = {
  modifier: { type: modifierType },
  eventHandlers: { type: listenersType }
}
```

**Comment by Frikki** [comment]
I think the first suggestion is more prone to typing errors, but the second introduces recursion in the validation.
