### ISSUE TITLE
Refactor state + props into single props object

### ISSUE THREAD

**Issue by lancejpollard** [dekujs/deku#144]
React and deku both expose an internal implementation detail, the idea of state and props. But it doesn't need to be this way, partly because it adds more to the api, but mainly because it makes certain situations very complicated to deal with.

**Dialog example**

One example is this. Say you have a dialog and you want to keep it in the DOM and show/hide it as necessary.

```js
export function render(component, setState) {
  let {props, state} = component
  let {onCancel, onConfirm} = props
  if (!state.open) return <noscript></noscript>

  return (
    <div class='Dialog'>
      <div class='Dialog-title'>Confirm?</div>
      <div class='Dialog-button' onClick={cancel}>Cancel</div>
      <div class='Dialog-button' onClick={confirm}>Confirm</div>
    </div>
  );

  function cancel() {
    setState({ open: false })
    onCancel()
  }

  function confirm() {
    setState({ open: false })
    onConfirm()
  }
}
```

Given the way that deku/react are now, if you create a dialog, then it would default to whatever default state you had. So it has to default to `open`, since it's a state.

But then when you close it (say from a "cancel" or "confirm" button), it will do `setState({ open: false })`. Now there is no way to _externally_ tell it to open again. Your only solution is to remove the dialog from the dom, and add it again.

**Table sorting example**

Say you have a table component, and you want to set the initial sorting:

```js
let sorting = { name: 'email', direction: 'ascending' }
<Table sort={sorting} .../>
```

But now, you want to have all the sort-_toggling_ logic inside the table component. So the `Table` might be implemented along the lines of:

```js
export function render(component, setState) {
  let {props, state} = component
  let {records, row, sort} = props

  let body = records.map(row);
  let head = columns.map(column);
  
  return (
    <div class="Table">
      {head}
      {body}
    </div>
  );

  function column(data) {
    return <Column onSort={onSort} name={data.name} direction={data.direction}/>

    function onSort() {
      // change table sorting
      let newSorting = { name: data.name, direction: changeDirection(data.direction) }
      setState({ sort: newSorting })
    }
  }
}
```

But that wont work because you passed in `props.sort` initially, now you can only change it with `state.sort`. Then you have to do all kinds of clever workarounds to get this to work.

If instead, there was just _one_ way to manipulate these "props" (which state and props should just be one thing), then you could do both of these cases easily:

```html
<Table sort={sorting} .../>
```

```js
export function render(component, update) {
  let {props} = component
  let {records, row, sort} = props

  let body = records.map(row);
  let head = columns.map(column);
  
  return (
    <div class="Table">
      {head}
      {body}
    </div>
  );

  function column(data) {
    return <Column onSort={onSort} name={data.name} direction={data.direction}/>

    function onSort() {
      let newSorting = { name: data.name, direction: changeDirection(data.direction) }
      update({ sort: newSorting })
    }
  }
}
```

```html
<Dialog open={true}/>
```

```js
export function render(component, update) {
  let {props} = component
  let {onCancel, onConfirm} = props
  if (!props.open) return <noscript></noscript>

  return (
    <div class='Dialog'>
      <div class='Dialog-title'>Confirm?</div>
      <div class='Dialog-button' onClick={cancel}>Cancel</div>
      <div class='Dialog-button' onClick={confirm}>Confirm</div>
    </div>
  );

  function cancel() {
    update({ open: false })
    onCancel()
  }

  function confirm() {
    update({ open: false })
    onConfirm()
  }
}
```

**Why separate state/props?**

The main reason React separated these imo is to prevent a problem that could be prevented in other ways: modifying data that will mess up the "immutable" aspect of the rendering process.

This can be prevented by adding a field to a `propType` definition, basically `private: true`, or `internal: true`. If it's internal only, and you want that enforced, then you can add that.

There is still the need to keep track of external vs. internal properties, but this can be invisible to the user. The internal ones "stick around" as new external properties are passed in is basically it. But from a usage perspective, you shouldn't have to be thinking about this internal implementation detail.

Thoughts?

**Comment by anthonyshort** [comment]
It's really interesting and I'd be curious to learn more about the exact reasons React split the two. Conceptually I can see why, but maybe there are some in-practice things we haven't thought of. This would certainly make cases you've mentioned easier.

Maybe there are ways to do this, like wrapping a component in another one to expose sorting (this is just something I've been thinking lately that's kind of relevant):

```jsx
function render ({ props, state }, setState) {
  function changeSort (type) {
    setState({ sort: type })
  }
  return <Table sort={state.sort} onSort={changeSort} />
}
```

Then you're controlling the props of the child component using state of the wrapper component, allowing the table sorting to remain stateless.

Also, there could be weird things with race conditions. The user might set some state, but then some external force changes the state too, then you change it to something else, and when it gets rendered again it might not be what you expect. I'm not sure here... Something about the control being on both sides seems like it could get hairy.

**Comment by lancejpollard** [comment]
Yeah I'd be interested in hearing why React did that too.

For the example there:

```js
function render ({ props, state }, setState) {
  function changeSort (type) {
    setState({ sort: type })
  }
  return <Table sort={state.sort} onSort={changeSort} />
}
```

People would experience that as a workaround, a confusing solution to a problem with the underlying system.

[![screen shot 2015-05-22 at 1 30 54 pm](https://cloud.githubusercontent.com/assets/28718/7779155/d1bc5b58-0086-11e5-9f05-abfa4257d629.png)](https://www.google.com/webhp?sourceid=chrome-instant&ion=1&espv=2&ie=UTF-8#q=workaround)

In this case, it means we can't do things in a natural way, and instead have to cleverly structure our components to get it to work, which makes it hard to reason about and more difficult to implement things with :)

**Comment by lancejpollard** [comment]
Hmm, maybe this was the reason for passing props to initialState?

**Comment by lancejpollard** [comment]
- https://github.com/glittershark/reactable/blob/master/src/reactable.jsx
- https://github.com/bgerm/react-table-sorter-demo/blob/master/jsx/app.jsx
- https://github.com/react-component/dialog/blob/master/lib/DialogWrap.js

**Comment by Frikki** [comment]
@lancejpollard The last DialogWrap.js link is dead.

**Comment by maxfrigge** [comment]
Wouldn't it be smarter to not keep sate inside a component at all? 
That way you get pure rendering functions.. props go in and you get a tree/dom in return.

**Comment by anthonyshort** [comment]
@maxfrigge yup! That's the plan. Completely stateless components.

**Comment by download13** [comment]
@anthonyshort That would make things a lot simpler and I like the idea of it, but what if a component needs to store some kind of internal state?

I usually need to store internal state when dealing with outside libraries. For example, storing a handle to a chart instance (needed to destroy it before re-render). Is there another way to deal with this?

**Comment by anthonyshort** [comment]
@download13 Each component has a unique path in the tree, e.g. `0.2.4.someKey.5` 

We can pass that path in with the model, and you'll be able to do whatever you want with it. If you're using something like redux, you would just dispatch an action to store state at that path. You could also just store it in a local variable and remove it when you're done.

It should provide the benefits of both a single state atom, and local state.
