### ISSUE TITLE
propTypes validation suggestions

### ISSUE THREAD

**Issue by voronianski** [dekujs/deku#146]
It will be nice to have support of:

- several types like `['boolean', 'string']`
- `instanceOf` property validation

**Comment by anthonyshort** [comment]
Maybe to keep things simple we could just allow `type` to be a function that is given a value and can return an error. 

If you want to open a PR for this we could definitely get it merge in :)

**Comment by voronianski** [comment]
@anthonyshort in this PR:

- [x] several possible types validation like `['boolean', 'string']`
- [x] accept `type` as `fn(valueToValidate)` that should return `true` in order to pass in

**Comment by voronianski** [comment]
@anthonyshort Thanks for merging!
