### ISSUE TITLE
Insert html on render

### ISSUE THREAD

**Issue by blup** [dekujs/deku#147]
I was looking for a way to insert a string which may contain html elements into the DOM. Something similar to React's ``dangerouslySetInnerHTML: {__html: string}`` . Is it currently possible?

**Comment by blup** [comment]
For now I'm doing the following workaround:
````coffeescript
  afterMount: (c, el, set) ->
    (d.innerHTML = d.textContent) for d in el.getElementsByClassName('class')
````

**Comment by lancejpollard** [comment]
Oh cool, yeah there is a way, you can just set 'innerHTML' attribute on a virtual node :)

    <div innerHTML={content}></div>

Let me know if that works for you.

**Comment by anthonyshort** [comment]
Just added it to the Readme
