### ISSUE TITLE
event.currentTarget is always <body>

### ISSUE THREAD

**Issue by voronianski** [dekujs/deku#148]
Noticed this bug as it prevents my widget from working properly :/

```javascript
let Element = {
    render() {
        function handleClick (e) {
            console.log(e.currentTarget, e.target);
            // `currentTarget` will be <body /> on clicking both elements
        }

        return (
            <div class="wrapper" style={{'width': '100%', 'background-color': '#f80', 'height': '10px'}} onClick={handleClick}>
                <div class="inner" style={{width: '50%', 'background-color': '#ddd', 'height': '100%'}}></div>
            </div>
        );
    }
};
```

**Comment by anthonyshort** [comment]
You'll probably want to use event.target or event.delegateTarget depending on what you're doing. Let me know if that helps.

**Comment by voronianski** [comment]
@anthonyshort I need to get access to wrapper element which has `onClick` handler. Just tried `delegateTarget` and it's exactly what I need. 

Strange I always used `currentTarget` for that purposes as it behaved similarly.

**Comment by anthonyshort** [comment]
We should document this better too. I'll add it to the list.
