### ISSUE TITLE
custom props validator

### ISSUE THREAD

**Issue by joshrtay** [dekujs/deku#154]
It would be nice to be able to use custom props validators. Would you guys be open to allowing users to override the built in validator by passing a validator function to deku. It could be something like this:

```js
var validator = require('is-my-json-valid');
app.option('validateProps', function (props, rules) {
  var validate = validator({ type: 'object', properties: rules});
  if (!validate(props)) {
   var err = validate.errors[0];
   throw new Error(err.message + ':' + err.field);
  }
});
```

**Comment by anthonyshort** [comment]
I've had thoughts about pulling the prop validation logic out of Deku, since it seems a little out of scope. It would be pretty easy to just manually called a function similar to what you have there in `render`. 

Is there any reason you want to do your own thing with it? We beefed up the functionality of the validation recently so you can set a function as the `type` value so you can do custom validation there.

**Comment by joshrtay** [comment]
I think it would be nice to have a full featured [JSONSchema](json-schema.org) validator, especially since I'll have schemas defined in that form client side for things like form validation. For example, if you had `user` and `project` schemas already defined, for the route example you could do:

```js
var propTypes = {
  route: { 
    source: 'currentRoute' , 
    type: 'object',
    properties: {
      name: {type: 'string'},
      path: {type: 'string'}
      resources: {
        type: 'object',
        properties: {user: user, project: project}
      }
    } 
  }
}
```

**Comment by lancejpollard** [comment]
:+1: @joshrtay yeah that would be sweet if it followed the JSONSchema spec

**Comment by anthonyshort** [comment]
This would be great. How would people feel about taking the validation out of Deku? You would just need to manually do your own validation in `render` by composing it with some other validator.

**Comment by joshrtay** [comment]
I think it would be good to take validation out of Deku, but I think doing manual validation in every render function is a bit tedious. Is there any middle ground? Could we create a global beforeRender hook, so that you can do something like...

```js
var validator = require('is-my-json-valid');
app.beforeRender(function (component) {
  var {props, propTypes} = components;
  var validate = validator({ type: 'object', properties: propTypes});
  if (!validate(props)) {
   var err = validate.errors[0];
   throw new Error(err.message + ':' + err.field);
  }
});
```

**Comment by anthonyshort** [comment]
Yup that sounds like a good idea! We'd just need to expose a hook in the renderer whenever props change for a component. We could provide a basic one as a plugin,

```js
import {validate} from 'dekujs/validate'
app.use(validate())
```

**Comment by dominicbarnes** [comment]
+1 for something more fleshed-out and documented like JSONSchema.

**Comment by anthonyshort** [comment]
### Option 1: Component-level validation

We could allow another validate function as part of the component. This would be called whenever the props are changed, and probably called just before `render`. This would require each renderer to call this function.

```js
function validate (props) {
  // 
}

function render () {

}

export { render, validate }
```

### Option 2: Add a function to the renderer

```js
render(app, document.body, { 
  validate: function (component) {
    // validate
  }
})
```

We could allow a validator on the renderer. This would mean you don't need to specify a validator on each component.

Thoughts?

**Comment by dominicbarnes** [comment]
For option 2, why exactly would you put a function at the top-level? Is that a "plugin" approach?

If we stick with a core validator, I think option 1 makes more sense considering deku's philosophy. If we want to remove that feature from core and make it pluggable, then option 2 (as far as I understand) is the better approach.

Option 3 is to keep the existing structure, but adopt JSONSchema as the validator instead. (this is my preferred option) Right now, there is zero docs on how to use `propTypes`.

**Comment by joshrtay** [comment]
@dominicbarnes I think the problem with adopting JSONSchema as the validator (option 3) is that you either have to implement your own full featured validator, which seems like it's outside the scope of this project or choose one of the existing validators, all of which are bit quirky (different error messages, different portions of the spec supported, different additions to the spec, different performance characteristics).

**Comment by joshrtay** [comment]
https://github.com/ebdrup/json-schema-benchmark

**Comment by anthonyshort** [comment]
I think we'll pull this out and allow it to be composed. Doing validation at the component-level makes things much simpler. I'm still trying to figure out the most functional way to do validation, but here's what I'm thinking:

```js
let template = function ({ props, state }) {
  return <div>{props.text}</div>
}

let render = compose(template, validate(propTypes))
```

If you want validation in all of your components, you can just create a simple abstraction to create components in your app. One of the goals of Deku is to be a low-level library for creating virtual DOM components, so it should aim to do that one thing really well. 

The next version `0.5.0` will have this change.

**Comment by mpal9000** [comment]
+1 for removing validation from the core. -1 for something non at the component level. I was thinking about a `validate` hook function that does nothing except controlling when the validation needs to be run. Then the `validateProps` app option could be removed.
