### ISSUE TITLE
html5 attribute

### ISSUE THREAD

**Issue by rhacker** [dekujs/deku#157]
Is there any way we can access html5 custom attribute through `event.target` in deku ? `event.target.attributes` is empty even the element has an attribute in it.

```js
function onClick(e, c) {
   // empty
   e.target.attributes
}
<button data-ok={false} onClick={onClick}>Submit</button>
```

**Comment by anthonyshort** [comment]
Attributes with a false value aren't added to the element. This is so you can easily do things like hidden={false}. Try using a string
