### ISSUE TITLE
Event throttling breaks onDrop

### ISSUE THREAD

**Issue by xdissent** [dekujs/deku#159]
A `drop` event is only fired by the browser if the most recently sent `dragenter` or `dragover` event was "handled" (`event.preventDefault()`). The event throttling blocks duplicate `dragover` events, so the `drop` event never fires - unless you happen to drop in the middle of an animation frame. Is there a technical reason for the throttling? I feel like it could be an unpleasant surprise in other scenarios as well. Rendering is already throttled per frame regardless of how many state updates happen, correct?

**Comment by anthonyshort** [comment]
It's really just stopping `handleEvent` from being called on high-frequency events like mousemove. That function walks up the tree looking for event handlers. There isn't any perf tests around it though so there's no proof that throttling is actually helping. 

And you're right about state changes being throttle per frame anyway. It might be worth taking out the throttle. The browser can probably run that millions of times a second anyway.

**Comment by anthonyshort** [comment]
@lancejpollard @dominicbarnes thoughts on this?

@xdissent If you want to make a PR with this, it's just changing this line: https://github.com/dekujs/deku/blob/master/lib/render.js#L1242 and updating the deps.

**Comment by dominicbarnes** [comment]
My thought is we should probably remove the throttling internally, that should probably be handled in user-land unless there's a demonstrated need to do that internally.
