### ISSUE TITLE
Alias "element" with "createElement" for JSX compatibility.

### ISSUE THREAD

**Issue by DylanPiercey** [dekujs/deku#162]
I'm not sure if it's the jsx compiler I am using but when supplying the

```javascript
// @jsx element
<input type="radio"/>
```

It transforms the jsx into:

```javascript
element.createElement("input", {
      "type": "radio"
    })
```

If we alias "element" with "createElement" (What react uses) it will resolve this issue and we can do:

```javascript
// @jsx deku
<input type="radio"/>
```

Which would become:

```javascript
deku.createElement("input", {
      "type": "radio"
    })
```

**Comment by anthonyshort** [comment]
Out of curiosity which jsx compiler are you using? I think babel and the jsx-tools used to work that way, but they changed it. If it's just the way one of the jsx compilers work then I don't mind adding this :)

**Comment by DylanPiercey** [comment]
Currently using the "coffee-react" transformer so it could just be that. Not sure what they use internally.

**Comment by anthonyshort** [comment]
Just pushed 0.4.4 that adds `createElement` as an alias :)
