### ISSUE TITLE
Error on rendering a list

### ISSUE THREAD

**Issue by blup** [dekujs/deku#165]
Sorry, I'm probably missing something obvious but I've been getting this error for a while now and I can't figure it out. I'm rendering a form with a sub-component called input:
````coffeescript
ContactForm = 
  render: ({props, state}) ->
    r 'div', class: 'container',
      r Input, {name: 'name', key: 'name', title: 'Name', onChange: onChangeName}
      r Input, {name: 'email', key: 'email', title: 'Email', onChange: onChangeEmail}
      r Input, {name: 'message', key: 'message', title: 'Message', onChange: onChangeMessage, textarea: true}

Input =
  render: ({props, state}) ->
    r 'div', class: 'row', key: props.name,
      r 'input', type: 'text', class: props.name, ref: props.name, onChange: props.onChange
      r 'label', props.title
````
The error I get is an undefined newEl at ````parent.insertBefore(newEl, target)```` in replaceElement, where the parent is 'container'. I thought I was missing the 'key' prop so I added it at both places but no luck.

**Comment by lancejpollard** [comment]
Yes! I have had this error too, but it's hard to reproduce. Can you create a test that reproduces the error? That would make it much easier to fix. Once this is fixed then lists will be pretty solid.

If you remove the key properties, it will work, so it has something to do with keys.

**Comment by anthonyshort** [comment]
Hrm, yeah the key diffing needs some work. It's currently a really basic implementation with way too many loops: https://github.com/dekujs/deku/blob/master/lib/render.js#L538 We just needed it to work for a project we were working on. 

If we can get a small test case it will make everything way easier to fix.
