### ISSUE TITLE
Safari is not happy with redefining class of a property

### ISSUE THREAD

**Issue by rhacker** [dekujs/deku#168]
I only have this problem when using Safari, it works fine with Chrome and Firefox (both latest version)
```
Attempted to redefine property 'class'
```

**Comment by anthonyshort** [comment]
Hrm, can you provide a test case? Is it the property on the DOM element?

**Comment by anthonyshort** [comment]
You'll get this in browsers if you just do this:

```
{ class: 'foo' } // error :(
```

However if you're assigning that object to something, it's fine: 

```
var m = { class: 'foo' } // works
fn({ class: 'foo' }) // works
```

**Comment by rhacker** [comment]
@anthonyshort sorry for late responding. And thanks for for your help :)
