### ISSUE TITLE
onSubmit does not seem to work

### ISSUE THREAD

**Issue by staydecent** [dekujs/deku#169]
I tried to copy the example form component from `examples/events` and just can't get the `onSubmit` event to fire. I also noticed it was not covered in the tests so there was not an easy way to check if I was doing something wrong.

Example:
http://requirebin.com/?gist=99fdbeb84c1ecd0a81a3

**Comment by anthonyshort** [comment]
Oh! Looks like you're trying to set the class with the element type. We removed this feature a while back. We need to update those examples.

You need to just do `dom('form', ...)`, not `dom('form.box' ...)`
