### ISSUE TITLE
A solution for mixins

### ISSUE THREAD

**Issue by pho3nixf1re** [dekujs/deku#174]
Is there a way to share functionality like with a ReactMixin? Or perhaps there is a better pattern than that? I noticed an interesting proposal in #19 from awhile back but that has not been implemented yet, or at least not as described.

**Comment by anthonyshort** [comment]
Because components are just objects, you don't need built-in mixin functionality. You can extend the object or compose functions instead. For example:

```js
// extending
import extend from 'extend'
import mySharedStuff from './shared'

let component = extend({}, mySharedStuff, {
  render: function(){
     // etc.
  }
})
```

```js
// extending
import compose from 'compose'
import validation from './shared'

let render = compose(validation, function({ props, state }) {
  // etc.
})

export { render }
```
