### ISSUE TITLE
Memory usage appears to be higher than other vdom implementations

### ISSUE THREAD

**Issue by ry5n** [dekujs/deku#180]
I’ve been doing some (admittedly amateur) memory profiling over at [http://vdom-benchmark.github.io/vdom-benchmark/](vdom-benchmark.github.io). It seems that Deku has considerably higher memory usage than other libraries. For example, in Chrome 43 on a 2012 MacBook Pro, maximum heap size was (in bytes I believe):

- Mithril: 34,890,576
- React: 38,155,840
- virtual-dom: 45,479,144
- Deku: 188,948,496

On mobile (Chrome 43/One Plus One) results were similar. Although max heap was less than half of these numbers, the relative values were about the same (I’ve made [timeline screenshots](https://www.dropbox.com/sh/p7rioa3lz2sdf1e/AACnL--eiH98AEFulLFw57Sia?dl=0) available, in case you’re interested).

I’m curious if this might be an issue, especially on memory-constrained devices or for memory-intensive applications.

**Comment by anthonyshort** [comment]
Thank man, this is awesome. We haven't seen anything noticeable in our app yet, but something like this could bite us later if we don't fix it. For that big of a difference there's probably something stupid we're doing that we could easily fix.

@dominicbarnes I know you'll be interested in this one :D

**Comment by xdissent** [comment]
I think it's just a bug in the benchmark implementation: https://github.com/dekujs/vdom-benchmark/blob/master/web/js/main.js#L39

I believe the `teardown` method should look like this:
```
BenchmarkImpl.prototype.tearDown = function() {
  this.renderer.remove();
  this.tree.unmount();
};
```

However, that hits some bugs (?) in render, which assume an element is always present. Specifically, `removeElement()` and then `isElement()` will get called with `undefined` and throw. Explicitly checking for an `undefined` element allows the benchmarks to run, and the teardown appears to have fixed all the leaks. Haven't tracked down *why* `removeElement()` is getting called with an undefined element yet.

**Comment by xdissent** [comment]
I guess #188 doesn't technically *fix* this issue without dekujs/vdom-benchmark#1, sorry about that.

**Comment by ry5n** [comment]
:+1:
