### ISSUE TITLE
Any syntactic sugar for CoffeeScript users?

### ISSUE THREAD

**Issue by jiyinyiyong** [dekujs/deku#181]
Hi, our apps are in CoffeeScript and personally I also use [CirruScript](http://script.cirru.org/). Since in CoffeeScript eveything is an expression, conditions like `if` and `switch` are such easier.

Is there any plan to add sugar for CoffeeScript or any language other than JSX?

At this moment I guess such code might work. Not sure whether this would change or not.

```coffee
div = deku.element.bind deko, 'div'

div className: 'demo',
  deku.component UserComp, data: {}
```

**Comment by anthonyshort** [comment]
We're probably not going to add any syntax enhancements specifically for CS, but there is the possibility of the vdom module being pulled out of Deku, so you'd be able to write it however you wanted to.

**Comment by jiyinyiyong** [comment]
Thanks.
I noticed there is "This may change in the future" in Component Specs. I thought most of them are stable.
But is there plan on changing APIs(which may cause the `deku.element.bind null, 'div'` solution fail)?

**Comment by anthonyshort** [comment]
Nope, the `element` syntax won't change. We need that to stay that way so it continues to work with JSX. It's just the internals that might change.
