### ISSUE TITLE
Event handlers functiion created at every re-render?

### ISSUE THREAD

**Issue by jiyinyiyong** [dekujs/deku#182]
Code here https://github.com/dekujs/todomvc/blob/master/client/todo-item/index.js#L26

Came from React, which puts methods on `this` and `render` looks clean, Deku's solution looks quite messy to me. And during every render, function like `onClick` in the example below are created.

```js
render: function() {
  var onClick = function(){}
  return <div onClick={onClick}>Click</div>
}
```

Would that cause performance issues? Would it bother features like hot module replacement?

**Comment by anthonyshort** [comment]
You can put the functions anywhere you want, the handlers are passed everything you'll need:

```js
function render (component) {
  return <div onClick={onClick}>Click</div>
}

function onClick (event, component, setState) {
  // do anything
}
```

In some of the examples we put the functions inside when they're really simple. Hope that helps!

**Comment by jiyinyiyong** [comment]
So that `onClick` is passed in with `component` and `setState`. Didn't notice that. It's helpful.

Also found in docs https://github.com/dekujs/deku#event-handlers
