### ISSUE TITLE
Throws error when only one item of many has key

### ISSUE THREAD

**Issue by jiyinyiyong** [dekujs/deku#184]
Just like React I added a `key` property to force rerendering. And is throws error in rerendering(after state changes):

```coffee
div class: 'a',
  div null
  div key: 'generated-from-data'
```

https://github.com/dekujs/deku/blob/master/lib/render.js#L648
![screen shot 2015-06-25 at 12 43 46 am](https://cloud.githubusercontent.com/assets/449224/8335927/4e361fc8-1ad3-11e5-804c-7b0158bca065.png)

I supposed that was because no `key` was detected and then `position` lost tracking of an element.
And it works after adding `key` to the other element:

```coffee
div class: 'a',
  div key: 'sidebar'
  div key: 'generated-from-data'
```

**Comment by anthonyshort** [comment]
At the moment we only support keys on component elements. This is just because of the way the events work. We'll probably fix this up soon. You'll always need to add keys to all siblings though. This limitation makes the diffing significantly simpler.

**Comment by foray1010** [comment]
My code:
```javascript
const expandTableCell = <div class='panel-width' />;
const mainPanelItems = [];
const subPanelItems = [];
const trees = props.trees;

trees.forEach((treeInfo, treeIndex) => {
  const targetPanelItems = treeIndex % 2 === 0 ?
    mainPanelItems : subPanelItems;

  targetPanelItems.push(
    <BookmarkTree
      key={treeInfo.id}
      treeIndex={treeIndex}
      trees={trees} />
  );
});

return (
  <div id='panel-box'>
    <div class='panel-row'>
      <div id='sub' class='panel'>
        {expandTableCell}
        {subPanelItems}
      </div>
      <div id='main' class='panel'>
        {expandTableCell}
        <Search />
        {mainPanelItems}
      </div>
    </div>
  </div>
);
```

I get the same error when I use key on `BookmarkTree`
> Uncaught TypeError: Failed to execute 'insertBefore' on 'Node': parameter 1 is not of type 'Node'

By debugger, `positions` is a Array(4) with only two element in index 2, 3, so the parameters in the first forLoop is
 
> childEl = undefined, newPosition = 0

As `positions`'s value is assigned by `leftNode.index` and `rightNode.index`, after tracing the value of:
```javascript
var leftKeys = reduce(prev.children, keyMapReducer, {})
var rightKeys = reduce(next.children, keyMapReducer, {})
```

I find that `prev.children` and `next.children` will include `<Search />` and `<div class='panel-width' />` which `key` is `null`

Therefore, after `keyMapReducer`, `leftNode` and `rightNode` is not start from index 0, and so as `positions`, It will then run `el.insertBefore(childEl, target)` where `childEl` is `undefined` and thus this bug occurs.

As I don't know much about the virtual DOM algorithm, should we just check if `childEl === undefined`, if true, `return true` to `continue` the loop.
