### ISSUE TITLE
Reference dom nodes.

### ISSUE THREAD

**Issue by DylanPiercey** [dekujs/deku#189]
React has a "ref" key that allows us to quickly look up a child of our component's actual dom node.

How is this done with deku?

**Comment by anthonyshort** [comment]
I usually just use the `event` object when I need to get access to the real elements. I've found you only really need them after mount, after a render, or when some event happens.

Is there anything you're trying to do that doesn't seem to work?

**Comment by DylanPiercey** [comment]
Sorry, I didn't realise that we had access to the root element during afterMount (where I needed it). Thanks!
