### ISSUE TITLE
Access to the setState function in the beforeMount hook

### ISSUE THREAD

**Issue by Yomguithereal** [dekujs/deku#192]
Hello deku! I am currently trying to bind some deku components to the update of a [Baobab](https://github.com/Yomguithereal/baobab) tree so I can keep them in sync with my centralized app state. The problem I face is that the `beforeMount` does not seem to expose the `setState` function.

I am not trying to say that you should be able to **use** this function in the `beforeMount` hook, which would be pointless, but that, if you are not able to access it in some way, you cannot bind a listener on the tree/cursors' updates that would update the component's state.

Are you using another particular pattern I would have missed to do so with deku right now? My first shot was to go like with React and make a wrapper or higher order component but I am currently stuck with this hook problem.

**Comment by anthonyshort** [comment]
Oooh that sounds awesome. I'd love to know how the implementation goes. 

Is it possible to use the `afterMount` hook to bind listeners? Or do you need it bound before the initial render?

**Comment by Yomguithereal** [comment]
I can certainly try that. I'll tell you how it went.
