### ISSUE TITLE
Some kind of context for component?

### ISSUE THREAD

**Issue by voronianski** [dekujs/deku#199]
In my deku component I need to persist an instance of a class entity per component. I don't want to pass it as prop and just need to create a class instance inside component. 

Unfortunately I **cannot** just assign class instance to a deku component object (like in React)  as `this` is binded to `null` (but why?):

```javascript
// some component
import SomeInternalClassAPI from './path/to/it';

export default {
  beforeMount(component) {
    this.someClassInstance = new SomeInternalClassAPI(component.props.clientId);
    // will throw error cannot assign to `null`
  },

  ...
}
```

Then I tried to use `component` as the context, but (see comments):

```javascript
// some component
import SomeInternalClassAPI from './path/to/it';

export default {
  beforeMount(component) {
    component.someClassInstance = new SomeInternalClassAPI(component.props.clientId);
  },

  render(component) {
    // on first render it contains `someClassInstance` field
    // but on the second render it's absent..
    return <div>...</div>;
  }
}
```

Do you have a workaround for this or any piece of advice?

**Comment by troch** [comment]
It seems a new component object (which is an `Entity.context`: ) is created for each render cycle. So nothing will persist on a component object, and it will always come back with only 3 properties: `id`, `props`, `state`.

Solution you currently have:
- Maintain your own registry using component id to store additional information (see #195)
- Store in state (not always idiomatic depending on what it is)

Would be nice to have
- Being able to access to the entity object of a component (as a reference on the component object itself, or like mentioned in #195)

**Comment by voronianski** [comment]
@troch 

> Would be nice to have
> - Being able to access to the entity object of a component (as a reference on the component object itself, or like mentioned in #195)

This will be huge!

**Comment by anthonyshort** [comment]
We don't let you attach things to this, because `this` is just a way to hide state. You can use the `id` and store it yourself but at least that's more explicit than `this` which is hidden and unpredictable.  So pretty much what @troch said :)
