### ISSUE TITLE
Equivalent of react's context

### ISSUE THREAD

**Issue by Yomguithereal** [dekujs/deku#200]
Hello deku, sorry if the issue has already been raised elsewhere but is there some kind of `context` (I mean like the React one, i.e. a way to make some data be propagated to all the descendants without explicit props passing) in deku edge right now?

My issue is the following: I need to pass a state tree instance along the app's hierarchy without having to pass it though props every time because this is really tiresome and because I don't want my app's code to rely on an instance of the state tree. Instead the state tree should be provided as an argument to the app.

```js
// I don't want that
var stateTree = 'whatever';

function renderApp() {
  // Using the stateTree, it's impure
}

renderApp();

// I'd like that
function renderApp(stateTree) {
  // This is pure
}

var stateTree = 'whatever';
renderApp(stateTree);
```

How is this kind of problem solved currently with deku? I am thinking about react contexts because this is the only option I know.

**Comment by anthonyshort** [comment]
Yeah I'm thinking about adding context into the next version and removing the `app.set` concept. Setting data on the app was like setting a context for the entire tree, but there was no way for components to set things on the app too. You could usually get around this by using some external store, but adding architecture like flux can be a huge pain in the ass. 

Context could make this job easier, but it could be a dangerous way to hide state.

**Comment by Yomguithereal** [comment]
I don't want to hide state :-). Once my composed components are branched to a state tree, they pass data from the tree as props to their "dumb" children. For now I can live with "clever" components relying on a `require/import` on a state tree's instance but this is hardly ideal when needing to propagate dependencies along an app's hierarchy, especially on the server side. But I also agree that the separation between a useful context and hidden state is very thin.

**Comment by anthonyshort** [comment]
Yup totally agree. That's similar to what we're planning on doing :)

**Comment by igl** [comment]
I just discovered deku and this was one of the first things i looked for :+1:
I would love this feature not for passing state `down` but to reasonably pass state `up` without manually passing hooks from the parent container to each of the many components i would like to compose.

**Comment by DylanPiercey** [comment]
+1

**Comment by anthonyshort** [comment]
This exists in 2.0. You'll just pass a context object to the `render` function each time. It can't be modified throughout the tree, so you just have the one object, available to all components.
