### ISSUE TITLE
Adding non-prop attributes to components

### ISSUE THREAD

**Issue by ashaffer** [dekujs/deku#201]
So, in my application I have a signup form.  Sometimes that signup form is on the homepage, and sometimes it is in a modal dialog.  When it's on the homepage, it's in a two-column layout that looks like this:

```javascript
function render() {
  return (
    <div layout='row' layout-align='space-between' layout-phone='column'>
      <Message flex='55' flex-tablet='80' flex-phone='95' />
      <SignupForm flex='55' flex-tablet='80' flex-phone='95' />
    </div>
  )
}
```

Those flex attributes are from google's material design stylesheet.  However, at the moment those attributes get interpreted as props, and get passed down to the components rather than being set on the outermost element of the component.  The SignupForm component shouldn't need to know about how its being laid out, since it can be laid out multiple ways in different places, it'd be nice if this was strictly the caller's concern.

So there are a few solutions I can think of, but none of them seem particularly great to me:

1.  Wrap Message/SignupForm in a div that has the attributes.  This has the downside of creating excess elements and just adding noise generally.
2.  Have an `attrs` prop by convention that copies its properties onto the outermost element of the component.
3.  Use function composition to decorate the components.  E.g.
    
     `const HomeSignupForm = attrs(SignupForm, {flex: 55, flexTablet: 80, flexPhone: 95})`
4.  Have some sort of special syntax that hints to deku that an attribute is not a prop and should be treated as a regular attribute.  E.g. 

    `<SignupForm $flex='45' />`
5.  Just place all props as attributes on the actual elements as well as passing them down.

Anyone have any better ideas or solutions?

**Comment by anthonyshort** [comment]
Normally in this case I'd just be wrapping it in another container instead. This feels more like composition to me.

```js
function render() {
  return (
    <div layout='row' layout-align='space-between' layout-phone='column'>
      <div flex='55' flex-tablet='80' flex-phone='95'>
         <Message />
      </div>
      <div flex='55' flex-tablet='80' flex-phone='95'>
        <SignupForm/>
      </div>
    </div>
  )
}
```

And it decouples the "layout" from the component. You could also just pass them all in like an object, but I don't like this as much:

```js
function render() {
  return (
    <div layout='row' layout-align='space-between' layout-phone='column'>
      <Message layout={{flex: '55', flex-tablet: '80', flex-phone: '95'}} />
     ...
    </div>
  )
}
```

Message: 
```js
function render({ props }) {
  return (
    <div {...props.layout}>
      Message here
    </div>
  )
}
```

> This has the downside of creating excess elements and just adding noise generally.

I personally don't worry about this too much anymore. I'd say having the composition is more important than noise which could be abstracted out. You could also wrap the commit 'layout' into it's own component and render that. 

```js
function render({ props }) {
  return (
    <TwoColumnLayout>
      <Message />
      <SignupForm />
    </TwoColumnLayout>
  )
}
```

And use `props.children` to wrap each of them. It depends how frequently you intend to use it I think.

**Comment by ashaffer** [comment]
Ya I think you're right.  It's probably cleaner for the layout to be completely independent of the component, even in cases where it isn't strictly necessary.  

That `<TwoColumnLayout>` idea is neat, I think i'll probably take that approach.  Thanks.
