### ISSUE TITLE
JSX-IR Adoption

### ISSUE THREAD

**Issue by NekR** [dekujs/deku#202]
I am not sure how this fits in your long term plan, but it would be to at least explore adoption of [JSX-IR](https://github.com/jsx-ir/) or at least write ``jsx-to-deku`` Renderer, but for that I will need some help because I am not so much familiar with deku.

**Comment by anthonyshort** [comment]
I'm down for this. All we need are objects that has a tag/type, attributes/props and children. Is that the default output of the renderer?

**Comment by NekR** [comment]
@anthonyshort Yes, that is all what you need to _handle_. ``{ tag, props, chidlren }`` is output from transpilation and next it's handled by the runtime/Renderers. So basically you will need to handle JSX-IR output in deku and that is all. But there is a thing with Babel plugins--Babel does not has a way to provide options for them, so if you need plugin with options different than default you need to ship it alongside with you lib. See this: https://github.com/jsx-ir/babel-plugin-jsx#advanced-usage-options

So usage of deku with JSX-IR and should look like this:

transpilation part
```js
babel.transform(code, {
  plugins: ['deku/babel-plugin'],
  blacklist: ['react']
});
```

and runtime part as usual (as I correctly understand it)
```js
import Button from './button'
import {tree,render,renderString} from 'deku'

let app = tree(
  <Button kind="submit">Hello World!</Button>
)

render(app, document.body)
```
 
Just not sure if with JSX-IR you still will need ``tree`` method. Probably just ``render`` should work fine.

**Comment by NekR** [comment]
Also you can of course generate JSX-IR by yourself if you have your own transpilation pipe line. I just think it's easier to reuse already created plugin.

**Comment by anthonyshort** [comment]
We're going to stick with the standard virtual element implementation, but we might add support for this if we get enough requests for it.
