### ISSUE TITLE
Crash: document.body is null (edge case)

### ISSUE THREAD

**Issue by Alpacatty** [dekujs/deku#203]
##### An edge case:
When omitting both `<head>` and `<body>` (technically valid, see [the spec](http://www.w3.org/TR/2011/WD-html5-20110525/syntax.html#optional-tags)), `document.body` can be `null`, causing Deku to crash on `addNativeEventListeners()`.

##### Solution
Attach the events to `document` instead of `document.body`.

**Comment by Alpacatty** [comment]
My initial solution was to attach events to `document.documentElement` (AKA `<html`) instead, considering
> An HTML document always has a root html element, even if the string <html> doesn't appear anywhere in the markup. - [the spec](http://www.w3.org/TR/2011/WD-html5-20110525/syntax.html#optional-tags)

but for some reason that only worked for the initial events added and afterwards just silently failed for some reason. Hmm.

Also created a PR for this: #204

**Comment by anthonyshort** [comment]
Fixed in #204
