### ISSUE TITLE
Not valid warnings in console - latest 0.4.10 version

### ISSUE THREAD

**Issue by voronianski** [dekujs/deku#208]
I've updated to latest `0.4.10` and started to receive such warnings everywhere:

```bash
deku: Using an objects and arrays for the class attribute is deprecated. You should use another module like https://www.npmjs.com/package/classnames
```

It's funny **but I'm already using this module everywhere in my components**:

```javascript
/** @jsx dom */
import { dom } from 'deku'; // eslint-disable-line no-unused-vars
import ClassNames from 'classnames';

export default {
    propTypes: {
        artworkUrl: {
            type: 'string'
        }
    },

    render(component) {
        const { props } = component;
        const classes = ClassNames('sb-soundplayer-cover', props.class);

        return (
            <div class={classes} style={{'background-image': `url(${props.artworkUrl})`}}>
                {props.children}
            </div>
        );
    }
};
```

**Comment by voronianski** [comment]
Also all the deku warnings should be removed in `NODE_ENV=production` build. For now they stay in built version as well making console cry :crying_cat_face:

**Comment by anthonyshort** [comment]
Woah, this was a mistake. I think they were in one of the branches I merged yesterday but they didn't get any testing. I've just pushed 0.4.11 that hides them behind process.env.NODE_ENV so you can use envify with production set to get these warnings.

**Comment by voronianski** [comment]
@anthonyshort but regarding my case there should be no warnings at all :)

**Comment by anthonyshort** [comment]
Yup fixed that :)

**Comment by voronianski** [comment]
@anthonyshort thanks a lot! :+1:
