### ISSUE TITLE
how not using array as children when using JSX

### ISSUE THREAD

**Issue by foray1010** [dekujs/deku#209]
How can I put an array as a child in JSX?
I cannot do something like `...props.children` like:

```js
<div>
  <div/>
  {...props.children}
</div>
```

Updated:
1:18:09 AM 
Saturday, July 25, 2015 
Standard Time +0000 UTC

**Comment by anthonyshort** [comment]
I'm not entirely sure what you mean, you should be able to do

````
<div>{props.children}</div>
```

**Comment by foray1010** [comment]
Oh sorry, I misunderstood the issue
this problem is exactly mentioned in https://github.com/dekujs/deku/blob/master/docs/hints/array-children.md

The following code will throw error, "TypeError: deku: Child nodes can't be an array. "
```
<div>
  <div/>
  {props.children}
</div>
```

I was asking about if there is any way to solve without changing the HTML structure using JSX
Or I will need to create a seperated DIV for storing props.children

If no, I would like to make a PR about `No solution for JSX` in array-children.md
