### ISSUE TITLE
TypeError: invalid 'in' operand obj

### ISSUE THREAD

**Issue by lancejpollard** [dekujs/deku#210]
Seeing this in Chrome IOS Mobile, thinking it could be because of this maybe, if `propTypes` is undefined:

https://github.com/dekujs/deku/blob/master/lib/render.js#L1150

Maybe for the moment we default it to `component.propTypes = component.propTypes || {}`.

**Comment by anthonyshort** [comment]
I might see if I can add this to run on CI too. But we could just do that for now.
