### ISSUE TITLE
Allow `children` to contain arrays

### ISSUE THREAD

**Issue by lancejpollard** [dekujs/deku#211]
It looks like recently the ability to use arrays in the virtual dom has been removed. However, it turns out to be a pretty common case, and the workaround is less than ideal.

Here are some examples off the top of my head where you want to use both objects and arrays in the body of a virtual node. Since these examples don't work, following them shows what you must do as a workaround.

_(I've run into this dozens of times the past couple weeks and had to modify the code into a complex form.)_

```html
<Tabs>
  <Tab name="Default tab"/>
  { otherTabs }
</Tabs>
```

There, the "default tab" is manually placed there, and always is there, but then you dynamically build a list of other tabs based on variables.

Here is a table example, where you have dynamic table cells, always followed by some action buttons:

```html
<Table>
  <TableBody>
    <TableRow>
      { dynamicCells }
      <TableCell>
        <Button>Standard action button</Button>
      </TableCell>
    <TableRow>
  </TableBody>
</Table>
```

Finally, here is an example where you show an alert/notice at the top of an array of sections.

```html
<Page>
  { alert }
  { sections }
</Page>
```

These are just a small sample of the cases where you mix both objects and arrays in the body of a virtual node. Because this has been removed, you first run into a confusing error message, then after you figure it out, you have to refactor to something like this:

```html
let allCells = dynamicCells;
allCells.push(
  <TableCell>
    <Button>Standard action button</Button>
  </TableCell>
);
<Table>
  <TableBody>
    <TableRow>
      { allCells }
    <TableRow>
  </TableBody>
</Table>
```

Which, that works, but it's much harder to see how the page is structured, there's a lot more searching and mental analysis required, which makes it less than simple.

Is it cool if we add this back in? The ability to use both arrays and objects in the body of a virtual dom.

cc @stevenmiller888 @anthonyshort

**Comment by lancejpollard** [comment]
The error that you see when you mix array/object is this:

![https://cldup.com/tT1s46jngj-3000x3000.png](https://cldup.com/tT1s46jngj-3000x3000.png)

Which isn't much help

**Comment by stevenmiller888** [comment]
+1

I've run into this a bunch of times. At a minimum, we should give a better error message IMO

**Comment by anthonyshort** [comment]
Hrm I thought JSX transformed it differently and actually expanded it out. We can add this back in and flatmap the children array.

**Comment by lancejpollard** [comment]
Another example is this:

```html
rows.push(<div class='Row'> { cells } </div>);
```

That expands to this:

![https://cldup.com/sHSAQqPtS7-3000x3000.png](https://cldup.com/sHSAQqPtS7-3000x3000.png)

So because there was extra space (which could be useful in some cases, or just a programmer error), it doesn't work and hard to debug.

**Comment by anthonyshort** [comment]
Yup cool, this should be fixed. It would be nice if the JSX was more intelligent, but this will work too.
