### ISSUE TITLE
Cannot set property 'pendingProps' of undefined

### ISSUE THREAD

**Issue by kevva** [dekujs/deku#214]
Yo, while setting some props on my tree I'm suddenly getting a `Cannot set property 'pendingProps' of undefined` error. It's some pretty basic code so I don't know why it weirds out on me like that.

```js
const app = tree(<App items={items}/>);

foo.on('change', data => {
    app.set('items', data.items);
});
```

**Comment by anthonyshort** [comment]
Hey @kevva, you shouldn't use sources AND set the prop.

```js
const app = tree(<App />);

foo.on('change', data => {
    app.set('items', data.items);
});
```

You either pass the props in, or use sources and let it pass them in for you.

**Comment by kevva** [comment]
Hm, strange, it works in some other places.

**Comment by anthonyshort** [comment]
I wouldn't rely on it working though, sources and props were intended to be two separate things. I don't think we have anything tested around using both of them.

**Comment by kevva** [comment]
Aren't sources accessed through props? I haven't found any docs that tells me otherwise.

**Comment by anthonyshort** [comment]
Yeah, but if you're setting that prop via sources and when you render, you'll never know which value it should be. This is a flaw in the design of the sources. We'll probably be implementing `context` like React  to make this sort of thing easier.

**Comment by kevva** [comment]
I'm still getting the error though, even when setting it properly.

**Comment by anthonyshort** [comment]
I'll probably need to see a larger example. Can you give a failing test case? Even something on requirebin would help.

**Comment by kevva** [comment]
Yo, this was due to a problem with my router. The use case for where I'm using deku is quite obscure so I'm initiating and mounting components separately. Somehow a component got initiated twice because of my router which caused this problem. Anyway, fixed now!
