### ISSUE TITLE
Doubt managing deku application with jspm 

### ISSUE THREAD

**Issue by thr0w** [dekujs/deku#215]
```javascript
var app = tree(<HelloWorld text="Hello World!" />)
``` 
being transplied to 
```javascript
app = tree(HelloWorld({ text: "Hello World!" }));
``` 
===
```javascript
<div>{props.text}</div>
``` 
being transpiled to 
```javascript
React.DOM.div(null, props.text);
``` 
=====

```javascript
babelOptions = {
    "optional": [
      "reactCompat"
    ],
    "jsxPragma": "dom"
  }
}
```
===

There is another babel option to set?

Sample application https://github.com/thr0w/deku-sample

**Comment by anthonyshort** [comment]
You might need to upgrade babel. It should transform that first example into:

```
dom(HelloWorld, {})
```

I'm not sure what reactCompat does though :)

**Comment by thr0w** [comment]
I'm using Babel 5.8.20 ( [see](https://github.com/thr0w/deku-sample/blob/master/config.js#L19-L20) )

without reactCompact throw "<" unexpected error.

Still unsolved.

**Comment by anthonyshort** [comment]
I'm not too sure how jspm works, so I might not be too helpful here. I've only tested Deku with Duo and Browserify. There could be something else going on that I'm not sure of.

**Comment by thr0w** [comment]
Don't worry, I'm just lerning jspm and deku simultaneously. I asked same question to jspm group, they say it's something with Babel but works well with Browserify and Duo.
Thanks!

PS.: If you wanna you can close it, I can continue this experiments for some weeks.

**Comment by anthonyshort** [comment]
Thanks, if you learn anything worth putting in the docs let us know.
