### ISSUE TITLE
Hot reloading support

### ISSUE THREAD

**Issue by Kureev** [dekujs/deku#216]
Hi all, I want to make a live-patch module for browserify (like https://github.com/Kureev/browserify-react-live but for deku), and as far as I can't take `react-hot-api` library from Dan Abramov, I would need to implement the same for deku. Could you help with considering best way to do it?

**Comment by anthonyshort** [comment]
I've been trying to figure out a way to get live reloading working. We could expose an API for it. Would you need every instance that deku has created? We store this in an entities object. It would be pretty easy to expose that, but there might be more we need to do.

**Comment by Kureev** [comment]
In react we're able to get tree of mounted components and retrieve their state to preserve it for updated components. So it works like this: exclude state -> replace component -> apply state. Now it's all about how to extract and apply state. Mb some inner implementation which allow me to do it? (Not sure it should be public)

**Comment by anthonyshort** [comment]
The state of all of the components will be stored on a single object that you'll be able to access. It's just an object with the mount id as the key and the state object as the value. We could expose methods for manipulating the state so that re-renders are triggered. 

I'd probably need to know in more detail what happens to make it work. But it shouldn't be too tricky.

**Comment by Kureev** [comment]
If you store component's state outside from component instance - it makes live-patch even easier! In classic variant it works like this: on change we replace mounted components(their prototypes) by new ones we got thru web sockets, then emit global `forceUpdate`. We can start from this I guess.

**Comment by Kureev** [comment]
If you're interested how it works on browserify level etc, you may [take a look here].(https://github.com/Kureev/browserify-patch-server)

**Comment by caspervonb** [comment]
Take a look at amok (http://amokjs.com)

Disclosure, I'm the author.

**Comment by anthonyshort** [comment]
This should be much easier to do now that components are all stateless. I want to get an example repo up and running showing how it's possible.

**Comment by anthonyshort** [comment]
This just work now. We have some docs on the site. :boom:
