### ISSUE TITLE
Cannot have multiple apps running

### ISSUE THREAD

**Issue by stevenhauser** [dekujs/deku#222]
There are some issues around running multiple apps at once and they all seem to revolve around attaching data to component definitions (which span across multiple app instances). This results in data being shared across app instances which can result in one app instance trying to access another app instance's data, or can result in bailing on creation or registration of certain internal data since an earlier app instance already created it.

1. [x] [Entities are stored on components definitions.](https://github.com/dekujs/deku/blob/master/lib/render.js#L1062) This is particularly problematic [when trying to update an entity due to a source change](https://github.com/dekujs/deku/blob/master/lib/render.js#L1102-L1106) because the `entities` in the `for` loop contain entities from _all_ app instances which results in one app trying to update another app's entity and it being `undefined` since that entity's id doesn't exist in the local scope.
2. [x] [Sources are stored on components.](https://github.com/dekujs/deku/blob/master/lib/render.js#L1085) Very similar to the first issue except in this case, [the function bails out early if `sources` already exists](https://github.com/dekujs/deku/blob/master/lib/render.js#L1080).
3. [x] [Component registration is stored on components.](https://github.com/dekujs/deku/blob/master/lib/render.js#L1050). This results in [early bailout](https://github.com/dekujs/deku/blob/master/lib/render.js#L1046).
4. [ ] [Component `sourceToPropertyName` is stored on component definition.](https://github.com/dekujs/deku/blob/master/lib/render.js#L1084). I haven't actually had any bugs with this yet, but it is similar to all the other issues. From what I can tell, this wouldn't actually be problematic but might as well handle it per app to avoid potential problems.

The solution for all of these seems to be associating internal data to a component within the scope of the `render` function. Using a `Map` or `WeakMap` would be great but does hurt browser support. Could be useful to `defineProperty` an internal `id` on component definitions and then a POJO could be used for all of the above cases.

Please let me know if you'd like me to implement fixes for these issues and PR them.

**Comment by anthonyshort** [comment]
Fixes for these would be great! However, it's probably worth knowing that we're going to be removing sources because it's expanding the scope of the module into more than just rendering virtual elements. It adds a lot of complication and sources become confusing when used in a larger app. We originally added sources quickly for an internal need we had, so the implementation isn't perfect.

I would love to be able to use `WeakMap` but it does kill browser support a fair bit. Whenever we can reasonable ditch support for IE10 we'll be able to use a lot more of these features.

**Comment by stevenhauser** [comment]
Cool, I'll work up a PR for this stuff and will probably do at least something for sources since I think it should be simple.
