### ISSUE TITLE
Preserving text selection in certain input types does not work

### ISSUE THREAD

**Issue by dominicbarnes** [dekujs/deku#229]
I didn't know this, but apparently some input types do not expose selection information:

```
Uncaught InvalidStateError: Failed to read the 'selectionStart' property from 'HTMLInputElement': The input element's type ('email') does not support selection.
```

I'm not sure of all the best solution here, seems like a bit of a minefield. (so maybe `try...catch` is the best approach?)

**Comment by dominicbarnes** [comment]
Actually, I found [this answer](http://stackoverflow.com/questions/21177489/selectionstart-selectionend-on-input-type-number-no-longer-allowed-in-chrome) (which also links to the spec/docs)

Seems like we should only attempt to preserve the selection data for inputs with the following types:
 - text
 - search
 - password
 - tel
 - url

**Comment by anthonyshort** [comment]
Woah, it could possibly just check for the property on the input first. The check is just looking for inputs, but it could just add that. A test for this would be good too.

**Comment by dominicbarnes** [comment]
Something tells me that even accessing the property is what's throwing the error, unless you mean something like: `if ('selectionStart' in el) { /* ... */ }`

Since it's already doing the check for `<input>`, I don't think it's unreasonable to add a `switch` for the type. (either way, a test would be good)

**Comment by anthonyshort** [comment]
Just wrote a test, waiting for CI to pass and I'll push 0.5.2 with this fix. It's crazy that the browser actually has the method on the element and throws an error if you try to call it. There doesn't seem to be any other way to check.
