### ISSUE TITLE
document 'magic' virtual elements

### ISSUE THREAD

**Issue by aeosynth** [dekujs/deku#235]
the readme mentions `magic-virtual-element`, but doesn't say when/why we should use it over `virtual-element`, and both `element` repos have blank readmes.

**Comment by foray1010** [comment]
after scrolling the source code, I think it is about syntax sugar for attribute, such as automatically join the array in attribute `class`  using `space`.

**Comment by anthonyshort** [comment]
Yeah we need to document both of those. I'll try and get them up this week.

**Comment by askmatey** [comment]
@anthonyshort Any progress ?

**Comment by anthonyshort** [comment]
Fixed thanks to @askmatey

**Comment by askmatey** [comment]
https://github.com/dekujs/magic-virtual-element/commit/aeed13e935e0ec152e7ca68b1af03be7d3d2080b
