### ISSUE TITLE
Suggestion: Don't update DOM if setState doesn't notice change and encourage immutable

### ISSUE THREAD

**Issue by foray1010** [dekujs/deku#236]
I know there are some guys changing the state's value directly in the state object, so setState cannot compare the difference.
But I think everybody should use something like `seamless-immutable` so that they don't directly modify the state, that is horrible and not a good practice in virtual DOM because we will need to update the DOM every time when running setState.
If we force not updating the DOM (or let say don't trigger render) if the state value is not changed in setState, I think people will start noticing this issue, plus it will improve the performance if nothing is actually need to be updated and we are able to know it because all the object and array is immutable.

**Comment by TEugen** [comment]
I don't understand, in what situation you would call `setState` and don't want to update the DOM?

**Comment by foray1010** [comment]
I set a function called `setRootState` as I would like to change the state directly in the child components without passing functions with `setState`
So, I cannot really check the current value of the root state. When I called setRootState, the state value may not be changed

Another situation is the state value is depended on function result, which is unexpected
```js
setState({
  isSomething: getIsSomethingFromSomewhereDynamically()
})
```
It is annoying to save the result and compare to the current value

**Comment by foray1010** [comment]
since seems no one is interested in it, I just close it
