### ISSUE TITLE
Feature: fetchData hook

### ISSUE THREAD

**Issue by blup** [dekujs/deku#237]
I was playing around a bit with https://github.com/erikras/react-redux-universal-hot-example/ , and one thing I found really convenient is the fetchData hook they use to connect the component to redux. It could just be a load() hook that returns a promise, which could then be injected into props (similar to sources). Just an idea.

Here's the logic behind it: https://github.com/erikras/react-redux-universal-hot-example/blob/master/src/universalRouter.js#L6-L27 , and here's an example use case: https://github.com/erikras/react-redux-universal-hot-example/blob/master/src/views/App.js#L124-L133 .

**Comment by anthonyshort** [comment]
We're probably going to avoid doing anything related to data loading with Deku and just delegate that work to other libraries.
