### ISSUE TITLE
Input range value not initializing correctly

### ISSUE THREAD

**Issue by blup** [dekujs/deku#239]
I'm not entirely sure this is a Deku issue, but for some reason the input range slider is not initializing correctly. I've tried breaking at https://github.com/dekujs/deku/blob/master/lib/render.js#L1292, and i noticed it doesn't change the value at all, and the slider's default value is either min or max. This is what I have on render():

```
<input class={classes} type="range" min={min} max={max} value={value} step={step}/>
```
The only way I've been able to make it work is to re-set the initial value on the element in afterMount.

**Comment by anthonyshort** [comment]
Hrm not too sure about this. I'll add a test for it and see if I can get it breaking.

**Comment by anthonyshort** [comment]
Any chance you could post a failing test case?

**Comment by anthonyshort** [comment]
I've added a test for this in 2.0.0 and it seems to be working. Closing for now.
