### ISSUE TITLE
Attaching values to component context

### ISSUE THREAD

**Issue by blup** [dekujs/deku#242]
I was trying to keep my unsubscribe handlers on the context object (like on the example: https://github.com/dekujs/deku/blob/master/docs/examples/counter/index.js#L23-L25), but i see the context object changes on each update: https://github.com/dekujs/deku/blob/master/lib/render.js#L987-L991 . How do you keep track of these from one render to another?

**Comment by anthonyshort** [comment]
You could either store them in state, or you could keep a mapping in the module at the top level

handlers[component.id] = unsubscribe 

Since it is state, I'd just keep it there personally.

**Comment by blup** [comment]
Thanks, i forgot the id was there as well. However, i wouldnt consider handlers as part of state. I ended up attaching them to the dom element in afterRender for now.

**Comment by anthonyshort** [comment]
Yeah, depends on how you define state really. I'd say because it's a type of state related to the component it belongs there even though it's not part of the render. But either way, it works :) 

It's probably worth adding this sort of thing to the docs too.
