### ISSUE TITLE
Style attribute no longer accepts objects?

### ISSUE THREAD

**Issue by voronianski** [dekujs/deku#250]
My old code with style attribute as object, for example `<div style={condition ? {color: 'red'} :  {}}>Text</div>` now returns weird `[object Object]`. So now style should accept only regular string - `<div style={condition ? "color: red" :  ""}>Text</div>`?

**Comment by anthonyshort** [comment]
Yeah we took this out because it's something that just belongs in another module. There are a few of them that do this, it lets you do things like include auto-prefixer which starts to get way out of scope for deku.

**Comment by 11111000000** [comment]
what simple (i.e. 'classnames') module can you use here ?

**Comment by 11111000000** [comment]
```{
      width: '80%',
      paddingBottom: '80%'
}```
=> 'width : 80%; padding-bottom: 80%'

**Comment by 11111000000** [comment]
found  `natew/object-to-css`
