### ISSUE TITLE
`0` value on inputs becomes `null` or empty

### ISSUE THREAD

**Issue by gillstrom** [dekujs/deku#253]
I noticed that a value of `0` outputs `null` or completely empty in inputs and options:

```js
<select>
	<option value={0}>hello</option>
	//=> value="null"
</select>
```

```js
<input type='button' value={0}>hello</input>
//=> value
```

```js
<input type='radio' value={0}>hello</input>
//=> value
```

Using version `0.5.6`.

**Comment by anthonyshort** [comment]
Well this is definitely a bug. You could cast the value as a string for now and that will work. But if you'd like to add a quick test for this it should be a pretty easy fix. Guessing we're using a loose false check somewhere
