### ISSUE TITLE
Development guide 404

### ISSUE THREAD

**Issue by tejasmanohar** [dekujs/deku#266]
https://github.com/dekujs/deku/blob/master/README.md#tests has a broken link

>Deku is built with Browserify. You can run the tests in a browser by running make test. Learn how to build and work on Deku [in the documentation](https://github.com/dekujs/deku/blob/master/docs/guides/development.md).

**Comment by anthonyshort** [comment]
Good catch, I think we that is a dead link at the moment. I'll get those back up ASAP. Thanks!

**Comment by tejasmanohar** [comment]
Thanks! Deku's test / build process is pretty heavy so that'd be great for outside contributors.

**Comment by shidhincr** [comment]
This is still broken ..

**Comment by anthonyshort** [comment]
Fixed: https://anthonyshort.gitbooks.io/dekujs/content/

**Comment by tejasmanohar** [comment]
whoop!
