### ISSUE TITLE
Join Chat / Slack link is broken

### ISSUE THREAD

**Issue by tejasmanohar** [dekujs/deku#281]
https://dekujs.herokuapp.com/ - heroku application error

I assume this pointed to something like [slackin](https://github.com/rauchg/slackin)

**Comment by kesla** [comment]
I'd be interested in joining a deku-slack organization! We're building a deku-app right now and it would be great to discuss/share thoughts in there!

**Comment by 11111000000** [comment]
+1

**Comment by anthonyshort** [comment]
I'll check this out this week. Thanks everyone :)

**Comment by anthonyshort** [comment]
There's a Discord link there now.

**Comment by kesla** [comment]
@anthonyshort what happened to this link?

**Comment by anthonyshort** [comment]
It got lost in the 2.0 merge. Added it back.
