### ISSUE TITLE
[doc] 'docs/guides/development.md' not found

### ISSUE THREAD

**Issue by princejwesley** [dekujs/deku#289]
`docs/guides/development.md` file is not found.

Below links are broken in `Readme.md` file:

- [Contributing to Deku](https://github.com/dekujs/deku/blob/master/docs/guides/development.md)

..Learn how to build and work on Deku [in the documentation](https://github.com/dekujs/deku/blob/master/docs/guides/development.md).

**Comment by tejasmanohar** [comment]
Should be closed as a duplicate of #266

**Comment by princejwesley** [comment]
@tejasmanohar Yes, it is. can you update the other ticket with `Contributing to Deku` link which is also broken.

**Comment by tejasmanohar** [comment]
same file
