### ISSUE TITLE
Example not running in Ubuntu 14.04 Chrome

### ISSUE THREAD

**Issue by dschalk** [dekujs/deku#290]
I used webpack to transpile
```javascript
import {render,tree} from 'deku'
var button = {
  type: 'button',
  attributes: { class: 'Button' }
}
// Create an app
var app = tree(button)
// Automatically re-renders the app when state changes
render(app, document.body)
```
into a file called 'bundle.js' in an index.html file. I've done this sort of thing before. I fired up my server, went to localhost:3000 in Chrome, and the following message appeared in the console log:
```javascript
	module.exports = function fastForEachObject (subject, fn, thisContext) {
	  var keys = Object.keys(subject),
	      length = keys.length,
	      iterator = thisContext !== undefined ? bindInternal3(fn, thisContext) : fn,
	      key, i;
	  for (i = 0; i < length; i++) {
	    key = keys[i];
	    iterator(subject[key], key, subject);
	  }
	};
```
"keys(subject)" was underlined in red. The popup message read: "bundle.js:2294 Uncaught TypeError: Cannot convert undefined or null to object".

Have I discovered a bug, or am I doing something wrong?

**Comment by troch** [comment]
You are missing `children: []` in button declaration. You should use `var button = element('button', {'class': 'Button'});` with element imported from `virtual-element`.`

**Comment by dschalk** [comment]
Thanks. I'll try to fix it.

By the way, I copied the code out of the Github repo README.md.

**Comment by dschalk** [comment]
I imported element from "virtual-element" and it works.

I had been puzzling over this example in the README:
```javascript
import element from 'virtual-element'
import {render,tree} from 'deku'

// Define our custom element
var App = {
  render: function ({ props }) {
    return <p color={props.color}>Hello World</p>
  }
}

var app = tree(<App color="red" />)
```
It imports "element" and doesn't use it. 

I am fleeing from the tyrany of React, and virtual-dom requires too much code. I hope deku works out for my projects. I am willing to make a pull request to clean up the README sample code, but I suspect that one of the maintainers would prefer to do it. 

Thanks again for the speedy response.
// And render it to the DOM
render(app, document.body)

**Comment by troch** [comment]
> It imports "element" and doesn't use it.

`element` will be used by the parsed JSX syntax.

> I am willing to make a pull request to clean up the README sample code, but I suspect that one of the maintainers would prefer to do it.

I don't know what the maintainers want to do:
- default children to `[]` where error occurs
- fix example with `element()`
- fix example with `children: []`

**Comment by anthonyshort** [comment]
@dschalk Would you be able to try this again with the new v2 and [docs](https://anthonyshort.gitbooks.io/dekujs/content/)?

**Comment by rcpacheco** [comment]
The docs link gives Error 404

**Comment by anthonyshort** [comment]
http://dekujs.github.io/deku

**Comment by rcpacheco** [comment]
Ah ok, the link that was in you comment was https://anthonyshort.gitbooks.io/dekujs/content/ That is the one that is giving the error.
