### ISSUE TITLE
Simpler getting started

### ISSUE THREAD

**Issue by m1sta** [dekujs/deku#301]
Deku is a great package but its learning curve for those new to build systems is harsh. I think the project would get better adoption if there was a simple two or three lines that a new user could run and be presented with a working deku sample page containing client-side jsx.

**Comment by rstacruz** [comment]
Unfortunately deku doesn't support client-side JSX, as far as I know.

**Comment by anthonyshort** [comment]
I've updated the documentation for v2. You can [find it here](https://anthonyshort.gitbooks.io/dekujs/content/). I'm always open to any suggestions for improving it. The docs are just in the repo, so feel free to open a PR also.

**Comment by rstacruz** [comment]
good stuff!

**Comment by m1sta** [comment]
404

**Comment by anthonyshort** [comment]
https://dekujs.github.io/deku
