### ISSUE TITLE
Document deku plugins

### ISSUE THREAD

**Issue by rstacruz** [dekujs/deku#305]
I see deku has support for plugins via `.use()`, but I see no docs on how to make plugins.

**Comment by kvnneff** [comment]
I've found a lot of explanations of ideas and architecture by searching through past issues. [This thread](https://github.com/dekujs/deku/issues/155) has some good info on plugins.

**Comment by rstacruz** [comment]
ahh, I guess this is a dupe of #155 then.

**Comment by queckezz** [comment]
Not sure if it's worth investing since 2.0 is right around the corner and as far as I can see, it's all based on a central store / state container, mainly redux. So plugins for deku will essentially be middlewares and are handled within redux.
