### ISSUE TITLE
Components without DOM nodes

### ISSUE THREAD

**Issue by rstacruz** [dekujs/deku#307]
Is it possible?

I'd like to write some components to set the document title and meta tags. I figured this can be done with a component that renders nothing, but performs `document.querySelector('title').textContent = '...'` or similar.

**Comment by rstacruz** [comment]
Here's what happens today:

```js
Component = { render() { return '' } }

render(tree(<Component />), document.body)
// Error: Render function must return an element.
```

**Comment by anthonyshort** [comment]
I'd probably have that as state outside of the component tree. It's not really related to the UI as much as it is the URL, and the URL is just a blob of context state.

In v2, using Deku alongside Redux, I'd have some middleware that handles the `document.title` change as a side-effect to a URL state change.

**Comment by rstacruz** [comment]
Curious: did you mean Deku v2 would have a hard dependency to redux?

**Comment by anthonyshort** [comment]
Nope, just using it alongside it to manage state. v2 makes it easy to use something like Redux, but you don't have to.

**Comment by rstacruz** [comment]
nice. :)

for what its worth, I was able to do this:

```js
// <DocumentMeta title={ "Hello" } />
module.exports = { render, afterUpdate }

function render () {
  return []
}

function afterUpdate({ props }) {
  const { title } = props
  setTitle(title)
}

function setTitle (title) {
  if (typeof document === 'undefined') return
  const el = document.getElementsByTagName('title')[0]

  if ('textContent' in el) el.textContent = title
  else el.innerText = title
}
```

**Comment by anthonyshort** [comment]
Yup that'd be the best solution. The lifecycle hooks are there for side-effects like that :)

**Comment by rstacruz** [comment]
...and this isn't really related to the issue, but I just want you to know that I'm really loving Deku so far.

If you're curious how your users utilize Deku: I've managed to hook up a setup with `deku`, `redux`, `deku-redux` and `riot-route`. All the router does is dispatch an action to the redux store, so everything is neatly and functionally rendered by a Deku tree from a Redux store.
