### ISSUE TITLE
v2 migration guide

### ISSUE THREAD

**Issue by rstacruz** [dekujs/deku#308]
Since v2 is just around the corner, it'd be nice to have a v1-to-v2 migration guide. Something like this:

> ### API changes
>
> | v1 | v2 |
> |----|----|
> | `deku.render` | `deku.dom.render` |
> | `deku.renderString` | `deku.string.render` |
> | `import element from 'virtual-element'` | `deku.element` |
> | `afterUpdate` | `onUpdate` |

**Comment by anthonyshort** [comment]
Great idea! Probably wouldn't take too long either.

**Comment by anthonyshort** [comment]
Started some work on it: http://dekujs.github.io/deku/docs/basics/migrating.html

It could use some more work, but that was just something quick I can put together tonight.
