### ISSUE TITLE
Not webpack friendly

### ISSUE THREAD

**Issue by queckezz** [dekujs/deku#309]
Requiring deku with webpack gives me the following warning:

![image](https://cloud.githubusercontent.com/assets/2580598/12017754/0a1212be-ad5b-11e5-90c8-649a64b86ebe.png)

This is because you built the final bundle with browserify which means that it has its own bundle context (require etc.)

I would suggest:
* Create a `dist/standalone.js` bundle for those not using any package manager (if you still wanna support that)
* Build source files to a `lib` folder through a prepublish step:
```json
// package.json
{
  "scripts": { "prepublish": "rm -rf lib && babel src --out-dir lib" }
}
```

I can't change this since I'm on a windows machine and don't have `make`.

Awesome work on `2.0.0-rc` btw! Really excited.

**Comment by anthonyshort** [comment]
This should be fixed in `2.0.0-rc4`, although I still need to fix #310
