### ISSUE TITLE
import { dom, render } from 'deku' not working

### ISSUE THREAD

**Issue by rstacruz** [dekujs/deku#318]
require('deku') returns:

```
{ default: { element, string, dom } }
```

Because:

```
export default {
  element,
  string,
  dom
}
```

It should instead be:

```
export { element, string, dom }
```

**Comment by anthonyshort** [comment]
Just fixed this in `2.0.0-rc5`

**Comment by anthonyshort** [comment]
Let me know if it's working correctly for you now. I'm going to remove all those default object exports. I didn't realize it was a weird thing with Babel :|

**Comment by rstacruz** [comment]
Working good!
