### ISSUE TITLE
Set up zuul

### ISSUE THREAD

**Issue by rstacruz** [dekujs/deku#319]
All travis builds are red right now.

You need to add `SAUCE_USERNAME` and `SAUCE_ACCESS_KEY` to Travis as detailed in https://github.com/defunctzombie/zuul/wiki/Travis-ci.

Personally, I prefer to add them in travis's repo settings page (contrary to zuul's docs) to keep your .travis.yml clean:

> ![](https://raw.githubusercontent.com/rstacruz/git-update-ghpages/master/docs/images/env-variables.png)

**Comment by anthonyshort** [comment]
Ya I missed that this morning. They've been passing for a while now though: https://travis-ci.org/dekujs/deku/builds
