### ISSUE TITLE
null nodes don't work anymore v2.0.0-rc5

### ISSUE THREAD

**Issue by rstacruz** [dekujs/deku#320]
Here's a simple component that uses the ternary operator to show something conditionally.

```js
module.exports = { render }

function render ({ props }) {
  return <div>
    { props.featured ? <span>Featured</span> : null }
  </div>
}
```

This now results in:

```
Uncaught TypeError: Cannot read property 'parentNode' of undefined
```

The workaround is to use an empty array instead:

```js
  return <div>
    { props.featured ? <span>Featured</span> : [] }
  </div>
```

**Comment by anthonyshort** [comment]
I tried to fix this up this morning, but I think it's going to take a little more work. For now, just replacing it with something like a `<noscript/>` should work. `null` should render as `<noscript/>` tags when I get it working correctly.

**Comment by rstacruz** [comment]
oh.. so thats what those noscript tags are for

**Comment by rstacruz** [comment]
couldn't nulls be handled in the same way as `[]`? empty arrays are common:

```js
items = [] // has nothing
<ul>
  { items.map((item) => <li>{ item }</li>) }
</ul>
```

(or do those turn out to be noscript's too?)

**Comment by anthonyshort** [comment]
Fixed in https://github.com/dekujs/deku/commit/9b9a26e094c97f91bd86559a2d9c127dfaaff1c8
