### ISSUE TITLE
Question: how do I get `dispatch` on the model?

### ISSUE THREAD

**Issue by rstacruz** [dekujs/deku#322]
`render`, `onUpdate` and other lifecycle hooks receive a model:

```
render ({ props, dispatch, path }) { ... }
onCreate ({ props, dispatch, path }) { ... }
```

But it seems the actual arguments of the model are:

```
{ props, children, path, context }
```

**Comment by anthonyshort** [comment]
This is probably a duplicate of #323. That's fixed, but it would have prevented the dispatch function being passed down correctly.

**Comment by rstacruz** [comment]
Haha cute, my code made it to the tests :P
