### ISSUE TITLE
1.0.0 is both a tag and a branch

### ISSUE THREAD

**Issue by rstacruz** [dekujs/deku#338]
This causes confusing when doing this, as this will always navigate to the branch:

![pasted_image_12_30_15__11_09_pm](https://cloud.githubusercontent.com/assets/74385/12052476/7306510e-af4a-11e5-803e-c2fc2ef0f12e.png)

The workaround is to use `^{}` (see `man gitrevisions`):

https://github.com/dekujs/deku/tree/1.0.0%5E%7B%7D

But perhaps it's better to rename the branch to `v1` or `v1.x` or similar.

**Comment by anthonyshort** [comment]
Fixed :)

Those were old PR branches
