### ISSUE TITLE
Question: will onCreate be called on string.render?

### ISSUE THREAD

**Issue by rstacruz** [dekujs/deku#341]

**Comment by troch** [comment]
It is not, onCreate / onUpdate / onRemove have to do with DOM elements.

**Comment by rstacruz** [comment]
Aye, makes perfect sense. Might want to note that in the documentation.

**Comment by anthonyshort** [comment]
That was the original idea, but there could be times when you are just dispatching actions on create. I think for now we'll leave them out and if someone needs them for a solid use-case we can add them in.
