### ISSUE TITLE
Thanks

### ISSUE THREAD

**Issue by Yomguithereal** [dekujs/deku#342]
v2 seems really awesome. Thanks for it :smile:! Can I help in some way?

**Comment by anthonyshort** [comment]
Thanks! I'm mostly trying to fix bugs that people are finding now, and I need to add some really simple examples. I wanted to do the simple Elm multiple counter example with hot reloading. Hot reloading should just work with Deku and not need any crazy transformers like React.

So however you want to help out would be great! :)

**Comment by rstacruz** [comment]
may i suggest cloning the repo and adding some test cases?

**Comment by Yomguithereal** [comment]
Added an example of HMR in #353.

**Comment by Yomguithereal** [comment]
Just added a simple repo displaying a setup for deku/redux HMR [here](https://github.com/Yomguithereal/deku-hmr-example).

**Comment by Yomguithereal** [comment]
If you like it I can link it to the docs in #353.

**Comment by Yomguithereal** [comment]
I added an example of HMR on the use cases of the [kotatsu](https://github.com/Yomguithereal/kotatsu) tool also.

**Comment by anthonyshort** [comment]
Woah that tool is awesome. Hadn't seen it before. Definitely going to use it.
