### ISSUE TITLE
dist folder

### ISSUE THREAD

**Issue by user471** [dekujs/deku#347]
Why there isn't dist folder in latest releases?

**Comment by anthonyshort** [comment]
It gets built on prepublish to npm, so we don't need to keep the built files in the repo. Is there some reason you needed it?

**Comment by user471** [comment]
Maybe I did something wrong.
```
npm build
browserify lib/index.js -o out.js
```
But the out.js doesn't have global deku object.

**Comment by rstacruz** [comment]
try `npm install`.

**Comment by anthonyshort** [comment]
@user471 is right, it won't give you the global, standalone version that way. We might need to make a `standalone` task that runs `browserify src/index.js -s deku -t babelify -o dist/deku.js`.

**Comment by user471** [comment]
>browserify src/index.js -s deku -t babelify -o dist/deku.js

It works. I think separate task would be useful

**Comment by anthonyshort** [comment]
Added it a `npm run standalone`

**Comment by troch** [comment]
Thought about rollup? It is better suited for publishing libraries than webpack or browserify (which themselves are better for building applications).

**Comment by anthonyshort** [comment]
I'd be ok with that, the tree shaking alone makes it awesome. If someone wants to just swap that out, go for it, I haven't actually used Rollup yet.

**Comment by troch** [comment]
Bundling to an IIFE is very good too instead of webpack or browserify exporting a variable but still having internal implementation of require. I'll make a pull request.
