### ISSUE TITLE
Rendering 0

### ISSUE THREAD

**Issue by Yomguithereal** [dekujs/deku#354]
The following:

```jsx
const Component = {
  render() {
    return <div>{0}</div>;
  }
};
```

will not render a text node containing the `0` string.

Is that expected behavior?

**Comment by rstacruz** [comment]
Thanks for trying it out, I believe this was previously discussed in #321 (and maybe #255). can you try it with the latest rc version?

**Comment by Yomguithereal** [comment]
I am using `2.0.0-rc7`.

**Comment by anthonyshort** [comment]
https://github.com/dekujs/deku/blob/master/test/createDOMRenderer.js#L127-L137

It's probably using some silly falsy check somewhere. It should be too hard to track down, but you might just need to follow the code path. It could happen in `element`, `diff` or `patch`.
