### ISSUE TITLE
Strange behavior with siblings with onClick

### ISSUE THREAD

**Issue by thriqon** [dekujs/deku#358]
I have this example: http://jsbin.com/famezem/3/edit?html,js Basically, it uses 2.0.0-rc8 to render two buttons, and overall clicks are counted.

However, it a) only updates the left button, and the click count does not increase by one, but doubles! This is caused by additional event listeners registered on that button.They are not removed during a render, because the previousValue passed to setAttribute is the handler for the right button , which is not removable from the left...

Am I doing something wrong here or is this a bug?

**Comment by rstacruz** [comment]
is this the behavior you're expecting? https://jsfiddle.net/rstacruz/uqtqhq55/

**Comment by thriqon** [comment]
Yes,exactly :)

**Comment by rstacruz** [comment]
jsbin wasn't working for me, so I pasted your example into jsfiddle. https://jsfiddle.net/rstacruz/dzc9gcyt/ @anthonyshort? :)

**Comment by thriqon** [comment]
FYI, if I change the definition of `MyButton` to the new function-only components introduced in rc8, it works as designed, compare https://jsfiddle.net/b6gk44kq/1/ and https://jsfiddle.net/b6gk44kq/3/

**Comment by anthonyshort** [comment]
I'll have a look at this issue soon, sorry about the delay!

**Comment by thriqon** [comment]
No worries, thanks anyways!

**Comment by thriqon** [comment]
Apparently also fixed in rc9 with https://github.com/dekujs/deku/commit/922634f9edf9383d6b1f6231797b5ad585f8a7f3 (in response to #366), now behaving as expected. Thanks!

**Comment by anthonyshort** [comment]
Great! Thanks for updating the issue
