### ISSUE TITLE
2.0.0 not usable via npm

### ISSUE THREAD

**Issue by 11111000000** [dekujs/deku#361]
I use in package.json:

```json
"dependencies": {
    "deku": "git@github.com:dekujs/deku.git#v2.0.0-rc8"
  }
```
but in `node_modules/deku` only some docs without `index.js`.
 
Try to manually clone 2.0.0-rc8, `npm install`, `npm build`, then symlink to current `node_modules` with no luck - `Module not found: Error: Cannot resolve module 'babel'`

**Comment by anthonyshort** [comment]
Any reason you're using the git url rather than the version? It seems like it could be something related to that, because it's working for others

**Comment by 11111000000** [comment]
yes, already found what "^2.0.0" works ok, closed
