### ISSUE TITLE
Problem on vnode attributes from JSX compile 

### ISSUE THREAD

**Issue by FlorentD** [dekujs/deku#366]
Hi all,
I've played with deku last days and I really enjoy it !
However I've seen something strange with the JSX compile,
With a DOM list, the id attribute of vnode created from the node seems to be wrong. It always equals to the size list. This seems to have sad effects on my app.
I suspect `babel-plugin-transform-react-jsx` for having bad behavior but not sure... maybe I'm doing wrong.

Here my repo de reproduce the problem : https://github.com/FlorentD/deku-jsx-problem

Thx !

![alt text](http://www.image-share.com/upload/3137/175.png "chrome console")

**Comment by anthonyshort** [comment]
Hey! Thanks for finding this. It looks like this is actually a bug with the way we're caching the result thunks (components). In that array of children, the cached rendered `<Card />`s are all the same. The output in the DOM looks right, but what this will do is lead to incorrect diffing on the next pass and we'll end up replacing nodes that we don't need to.

I've added a test for it now and I'm going to track it down.

**Comment by anthonyshort** [comment]
Ok I've figured this out. I'll have a fixed push up shortly along with a test. 🤔

**Comment by anthonyshort** [comment]
This is fixed in rc9. Thanks again :)

**Comment by FlorentD** [comment]
Thank you !! My app works now like a charm !! :-)
