### ISSUE TITLE
Can't read property 'childNodes' of undefined

### ISSUE THREAD

**Issue by rstacruz** [dekujs/deku#367]
I'm not sure what's causing this exactly:

![pasted_image_1_8_16__10_36_pm](https://cloud.githubusercontent.com/assets/74385/12200150/3bf3597c-b658-11e5-9729-02f017210962.jpg)

**Comment by anthonyshort** [comment]
Probably going to need a bigger test case :P

**Comment by anthonyshort** [comment]
Can you try this again with rc11?

**Comment by rstacruz** [comment]
still getting the same.

**Comment by rstacruz** [comment]
I'm also getting this:

> Uncaught TypeError: Failed to execute 'removeChild' on 'Node': parameter 1 is not of type 'Node'.

```js
            removeChild: function removeChild(index) {
              DOMElement.removeChild(childNodes[index]);
            },
```

likely because I have nulls in my `render()`:

```js
  return <div class='app'>
    { action ?
      <div class='nav'>
        <NavigationShow action={ route.get('action') } />
      </div> : null }

    { context.get('_loading') ?
      <LoadingIndicator /> : null }

    { context.get('error') ?
      <ErrorsShow error={ context.get('error') } /> : null }
   ...
```

**Comment by rstacruz** [comment]
Also this:

> Uncaught TypeError: Cannot read property 'type' of null

```
var isThunk = exports.isThunk = function isThunk(node) {
  return node.type === '#thunk'; // <===
};
```

> isThunk  @ index.js:107
> removeThunks  @ patch.js:109
> removeThunks  @ patch.js:122
> ...
> replaceNode  @ patch.js:91

I'll try to contribute isolated test cases when I get the time.

**Comment by anthonyshort** [comment]
I added the ability to render `null` last night. So hopefully this fixes all of these issues.
