### ISSUE TITLE
attr `selected` is not working

### ISSUE THREAD

**Issue by foray1010** [dekujs/deku#376]
console returns to me that https://github.com/dekujs/deku/blob/1d0d3385ad6e9fe498a63b940d59ef9b826578e3/src/dom/setAttribute.js#L62 cannot get `options` from `null`
I tried to print `DOMElement.parentNode`, it is `null`
I guess it is because it runs before the element is mounted to the parent

**Comment by anthonyshort** [comment]
Ah yeah that would make sense. We should set the attribute value as well for that initial render and it should work fine. Should be a small test and fix for that.

**Comment by anthonyshort** [comment]
Just pushed a test and a fix for this in rc13. Let me know if this is working ok for you now.

**Comment by foray1010** [comment]
It is working for me, thanks!
