### ISSUE TITLE
setAttribute for svg element

### ISSUE THREAD

**Issue by alepop** [dekujs/deku#379]
Hello! I have problem with rendered SVG element (no displayed but rendered).
Method `setAtribute` set SVG `namespace` for each attributes that tested with 'is-svg-attribute' module, but SVG native attributes do not share the SVG namespace. If I set `namespace` to `null` in `DOMElement.setAttributeNS` everything went fine. Can I create Pull request or I'm wrong?. Thanks!

**Comment by anthonyshort** [comment]
Thanks! If you could show me an example where it's breaking, we should be able to write some tests and fix it. If you want to take a crack at it, just add a failing test in `tests/` and run `npm test`. I'm happy to accept a PR with a fix (or even just a broken test that we can use to reproduce)

**Comment by anthonyshort** [comment]
Fixed!
