### ISSUE TITLE
is the basic example complete?

### ISSUE THREAD

**Issue by 0a-** [dekujs/deku#386]
Hi. I am pretty interested in deku. I've given the v2 doc some read-up and I am looking for some nice v2 demo for better illustration of the library. (I'm thinking about using it in some upcoming projects) I found the basic example in `/examples/` and I tried 

``` 
budo examples/basic/index.js -- -t babelify
```

after `npm install` but nothing really happens. 

Is the basic example complete? I found [this thread](https://github.com/dekujs/deku/issues/306) but the basic example isn't mentioned there. (p.s. I haven't worked with budo before so by reading the source I couldn't tell if the basic example is complete)

**Comment by 0a-** [comment]
Interesting. I went for a nap and when I woke up the server has started
<img width="1025" alt="screen shot 2016-01-22 at 2 54 15 pm" src="https://cloud.githubusercontent.com/assets/10269911/12504405/1b6a9d6c-c118-11e5-8966-adf7cb48c7b5.png">

**Comment by 0a-** [comment]
Turned out it was because I have proxychains4 on in my env. Budo is not compatibility with it. https://github.com/mattdesl/budo/issues/129

**Comment by anthonyshort** [comment]
> I went for a nap

Hah! Well, I'm glad you figured it out.
