### ISSUE TITLE
onCreate and DOM effects

### ISSUE THREAD

**Issue by 11111000000** [dekujs/deku#389]
rc-15
I try to inject some generated content to  `<div id={ path }></div>` in SomeComponent with it's onCreate hook  ( middleware is better, yes), but I found `getElementById(path) == null` (after next rendering (or HMR), things are on its places). Is this ok? I think, in 1.0 on first `afterRender` DOM are already generated.

**Comment by anthonyshort** [comment]
Yeah that's expected behaviour. You'll need to do something like `setTimeout(fn, 0)` or `requestAnimationFrame(fn)` to manipulate the DOM element.

**Comment by 11111000000** [comment]
Ah, yes, thanks
