### ISSUE TITLE
Question: Custom attributes

### ISSUE THREAD

**Issue by 11111000000** [dekujs/deku#402]
Example case: instead of `<input onKeyDown={ handleDivKeyDown }  />`  when user only want to handle  *Enter* key, we prefer to code like this: `<input onPressEnter={ doJob } />` .  Is there some dekujs-way?  Or maybe better to use `<SuperInput with={neededFeatures} />` ?

**Comment by ashaffer** [comment]
You could accomplish this with a custom `element` function.  E.g.

```javascript
import _element from 'virtual-element'

function element (tag, attrs, ...children) {
  forEach(attrs, (val, key) {
    if (key === 'onPressEnter') {
      delete attrs[key]
      attrs['onKeyDown'] = function () {
        if (e.which === 13) {
          val(e)
        }
      })
    }
  })
}
```

My personal preference for this though is to have an element function that accepts a map, like this:

```javascript
function render () {
  return <input onKeyDown={{enter: doJob}} />
}
```

I've made a small library [keychord](https://github.com/micro-js/keychord) that would be useful for this.

**Comment by 11111000000** [comment]
Awesome! Thanks you!

**Comment by ashaffer** [comment]
I went ahead and created the module: [event-handler](https://github.com/micro-js/event-handler).

**Comment by 11111000000** [comment]
Solved completely!

**Comment by anthonyshort** [comment]
Great! I was basically going to suggest the same thing :) Going to add a tag to this so I remember to add it to the docs.
