### ISSUE TITLE
Question: undefined content in vnodes

### ISSUE THREAD

**Issue by 11111000000** [dekujs/deku#403]
What is a common way to handle undefined content inside tags:
```
return (
  <div>{ something }</div>
)
```
which thrown errror if `something` is `undefined`.

Now we code like this:
```
return (
  <div>{ something ? something : '' }</div>
)
```
but too many hard to maintain conditionals is a pain!

I miss something, or how to implement:
```
return fixUndefined(
  <div>{ something }</div>
)
```
...or maybe there is a other, better way to do that and other validations? (may be with redux?)

**Comment by 11111000000** [comment]
Decomposition:
```jsx
...
return (<TextField content={something} />)
...
```
where
```
const TextField ({props : {content}}) => (<div class="text-field">{ content ? content : '<span></span>'}</div>)
```

**Comment by anthonyshort** [comment]
You can also use a `null` value. That will be transformed into a `noscript` tag during the diff.

```js 
let something = null
// Some logic...
return (
  <div>{ something }</div>
)
```
