### ISSUE TITLE
Cannot npm install from github

### ISSUE THREAD

**Issue by danwad** [dekujs/deku#414]
2.0.0-rc16 is the latest version on npm, but there are some changes I'd like from master.

From a bit of googling, I found that I can do this by installing from github with `npm install --save dekujs/deku`

However, `.npmignore` prevents `src` from being included when the package is installed so `require('deku')` fails.

Should the build directory `lib` be committed to the repo?

What is the recommended way of using bleeding edge deku?

**Comment by rstacruz** [comment]
> What is the recommended way of using bleeding edge deku?

There isn't one, unfortunately. This is an issue for all npm repositories with its built code not committed to the repo, or not updated regularly.

Here are some workarounds:

- Clone `dekujs/deku` first.
- If you want to use it locally, just run `npm link`. Then in the repo you'd like to use it in, run `npm link deku`.
- You can also publish it as `@danwad/deku` by changing `package.json`'s name to that, and change the version as you like, then publish using `npm publish --access public`.

**Comment by danwad** [comment]
`npm link` works well - thanks :)
